### ISSUE TITLE
Slic3r generating gcode with missing sections within a layer

### ISSUE THREAD

**Issue by antfurn** [alexrj/Slic3r#1193]
Hi,
Slic3r v0.9.9

I have an openSCAD object I designed, a key fob, that when Slic3r generates the gcode - parts of two of the columns get missed out on some layers.
![missing area](https://f.cloud.github.com/assets/4171512/564236/598b7392-c54d-11e2-9dbe-b71c6eee35de.png)

Happy to send the scad, stl and gcode files.

Thanks, Antony

**Comment by alexrj** [comment]
This was not a but but it was just caused by too thin sections in the original file.  Slic3r is now more tolerant though as many users are more concerned about missing extrusions rather than extrusion collisions.  This is how the supplied object looks like as of 1.2.6-dev:

![schermata 2015-01-30 alle 21 45 20](https://cloud.githubusercontent.com/assets/594957/5983013/796729ca-a8c9-11e4-81df-eb5c5deee855.png)
