### ISSUE TITLE
New support (0.9.11-dev) on top of part, and not supportive enough

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#1408]
I created a parabola, and tried slicing and printing it. 

Slic3r 0.9.10b works ok, but the support material isn't ideal. When printing perimeters at 0.1 and infill at 0.3, support is printed at 0.1. I guess this has been fixed in new support, so I'm eager to try that!

Slic3r 0.9.11-dev (current git head, ed0344e8), lays support right on top of the part itself alternating the first few layers with part and support being printed right on top of each other. Then, after a few layers, support is suddenly not written any more. I haven't made measurements, but I think this overhang is steep enough to warrant some more support material, even if "detect overhangs" is enabled.

STL: http://kefirshare.dreamhosters.com/parabola.stl

GCODE 0.9.10b: http://kefirshare.dreamhosters.com/parabola_20130825-001848_0.9.10b.gcode

GCODE 0.9.11-dev: http://kefirshare.dreamhosters.com/parabola_20130825-001420_0.9.11-dev.gcode

Slic3r config embedded in gcode.

This may be the same issue as #1376 but it's also different in some respects, so I've created a new issue.

**Comment by lordofhyphens** [comment]
Looks like it works in 1.3.0-dev, so far as I can tell. The support non-generation looks to be as expected as well (there isn't an overhang here). 

![parabola](https://cloud.githubusercontent.com/assets/31754/16168543/ca3ad55c-34cf-11e6-98fa-06f57afe4242.png)
![layers-1](https://cloud.githubusercontent.com/assets/31754/16168542/ca39c6d0-34cf-11e6-9fc5-4f7ebaf31f3e.png)

Closing. Please reopen if these pictures look to you like there is still a problem.

**Comment by bubnikv** [comment]
I shall comment on this kind of geometry. In my opinion this half sphere is not printable with such a little support simply because its weight is not sufficiently supported by the tiny support and the angular moment of the nozzle on the support is high if the print warps up a bit, making the risk of knocking the part off the bed very high.

This is an issue of all the slicers, which build the support based on analyzing the relations of the successive layers only. For example, Cura makes the same errors.
