### ISSUE TITLE
Support Material and missing layer

### ISSUE THREAD

**Issue by pegasocube** [alexrj/Slic3r#1729]
I have some problem with support material at 0.2mm layer (or more). When i generate the slice I see some layer blank (except the support material).

this is the complete code:
![image](https://f.cloud.github.com/assets/6469481/1972220/5ef52156-8344-11e3-80e7-5b10244b98f1.png)

This is the Layer 4 of 127:
![image](https://f.cloud.github.com/assets/6469481/1972233/9df0a70e-8344-11e3-81da-8b1e9007a5d6.png)

This is the Layer 5 of 127:

![image](https://f.cloud.github.com/assets/6469481/1972235/a9b162c2-8344-11e3-893e-ec13765e5261.png)

This is the Layer 6 of 127:

![image](https://f.cloud.github.com/assets/6469481/1972237/b5751f36-8344-11e3-8023-c9d901f05281.png)

And this is the Layer 7 of 127:

![image](https://f.cloud.github.com/assets/6469481/1972244/c5ef8112-8344-11e3-93fb-5b403e13fb44.png)

it seems that sometime the support material is generated on a different layer from the rest of the design.

can someone help me?

**Comment by Bertuc** [comment]
Hi everyone, sorry for digging this up but I may have found what's wrong.

I was trying to use the support feature with interface but I notices that there seemed to be suppornt only every other layer. I actually noticed, when using directly Slic3r rather than Repetier's preview, and checking layer heights rather than layer count, that the support DOES NOT take your layer height into account!

I'm printing in 0.2mm (support is green, perimeters yellow and red infill)

Layer 1, 0.2mm
![1](https://cloud.githubusercontent.com/assets/14875233/10140322/32429312-6607-11e5-982b-386d0aa74a81.PNG)

Layer 2, 0.4mm (notice, no additional support)
![2](https://cloud.githubusercontent.com/assets/14875233/10140350/63b23b8c-6607-11e5-96c2-4e1c42ac1e34.PNG)

Layer 3, at 0.5mm!! (and 2nd layer of support)
![3](https://cloud.githubusercontent.com/assets/14875233/10140413/a0d2af92-6607-11e5-8256-b89a56b0f1a2.PNG)

And so it goes on, next layer at 0.6, no support, then 0.8, both support and part, 1.0, no support, 1.1, only support... So starting from 0.2mm, there will be support only every 0.3mm, ingoring my 0.2mm setting.

I hope I helped pointing out the issue, I couldn't find anything on the Internet relating to this default layer height issue in support.

And sorry if there is any English mistake, not my native language ^^

**Comment by kefir-** [comment]
Slic3r does this on purpose. It prints support layers as thick as possible, regardless of your part's layer height. It saves lots of time, and you're just going to discard the supports anyway. Nice feature.

**Comment by Bertuc** [comment]
Unfortunately, that's what's preventing me from printing properly, my nozzle doesn't print correctly at .3mm, and my PVA interface layers can't print properly on poorly printed PLA... It would be a nice feature if you could actually modify that parameter to comply to what you want, time saving or quality. I need my supports strong so I can put the PVA.

**Comment by printingin3d** [comment]
Both of my printers have 0.35mm noozle. And it is basically impossible to print a 0.3mm layer with a 0.35mm noozle - so it would be awsome if that would be a parameter too. I cannot print with support because of this behavior.

**Comment by jweob** [comment]
I have the same issue. I have a 0.3mm nozzle and usually print at 0.1mm layer height. I have wondered why support never seems to work for me and has missing layers - now I know!

**Comment by frank2288** [comment]
I'm having the same problem. Anyone has a solution?

**Comment by pyrophreek** [comment]
Try increasing the extrusion width for support.  I found I had to increase it to 0.5 or 0.6 (and as a result slow down support print-speed a bit) to get good adhesion of support.  I believe I read in another post somewhere that there is a miscalculation in the extrusion for support material, and so it tends to make the extrusion widths smaller than actually set (don't remember where I read it).

**Comment by Patola** [comment]
We can turn this on and off for infill, why we can't do it for support?

On Fri, Dec 25, 2015 at 4:45 PM, pyrophreek <notifications@github.com>
wrote:

> Try increasing the extrusion width for support. I found I had to increase
> it to 0.5 or 0.6 (and as a result slow down support print-speed a bit) to
> get good adhesion of support. I believe I read in another post somewhere
> that there is a miscalculation in the extrusion for support material, and
> so it tends to make the extrusion widths smaller than actually set (don't
> remember where I read it).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexrj/Slic3r/issues/1729#issuecomment-167257118>.
>



-- 
Cláudio "Patola" Sampaio
MakerLinux Labs - Campinas, SP
Gmail <patola@gmail.com> - Mail EAD <patola@techtraining.eng.br> -
MakerLinux <patola@makerlinux.com.br> - YOUTUBE
<https://www.youtube.com/user/makerlinux>!
Facebook <https://www.facebook.com/patolinux> - Facebook da MakerLinux
<https://www.facebook.com/makerlinux> - Lattes
<http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4763932Z5>

**Comment by lordofhyphens** [comment]
Fine, fine, I'll dig out an option to set the support layer height (probably relative to the nozzle, although I can see that causing all kinds of UI headaches even with a tooltip, but setting it relative to the layer height also breaks existing behavior).

**Comment by burdickjp** [comment]
I was digging through the code some yesterday. I'm not a Perl programmer, I'm most comfortable in Python, but if you can point me in a direction I might be able to contribute. I'm currently looking for the behavior which allows the combination of infill layers. I'm thinking that's a good start for how UI, tooltips, etc. operate, but I'm having trouble finding it.

**Comment by lordofhyphens** [comment]
Going to close this, please put further discussion in #3377
