### ISSUE TITLE
Feature Request: Dual extrusion skirt

### ISSUE THREAD

**Issue by Nohtal** [alexrj/Slic3r#1780]
Is there a way we could integrate double skirts for dual extrusion prints? This would be similar to what makerware has for their 3D printers. After testing with dual extrusion for a while now I can tell you that this is much more useful than than the temperature Ooze control already build in.

**Comment by RepRapMe** [comment]
Triple extrusion skirt would be neat too

**Comment by jonaskuehling** [comment]
Finetuning dual extrusion printing for a while now we found to achieve much better and massively faster results without the currently implemented "ooze prevention" and delta-T idle-temperature. For many material we had major difficulties with too much friction inside the nozzle and thus extruder slipping due to the cooling-down and re-heating procedure, the reactivation of a previously idle extruder wasn't reliable at all. Now that we totally ignore this feature and only use retract-on-toolchange with quite a significant length we achieve almost no oozing at all with 0.35mm nozzles and ABS material, while all nozzles stay at target temperature. The tool change time is near to zero (retract&compensation for toolchange only) which incredibly fastens up dual extruder prints and let them almost compete with single extruder prints in terms of total print time.

The only bad thing about this: In those rare cases, where one extruder isn't used for a longer period/count of layers (like no support material needed for several layers, or think of the famous dual-color traffic cone..) the total amount of oozed material can sum up to a value that makes restart on the next layer where it's used again difficult without priming. Additionally some materials suffer from the long dwell time (degeneration) kept at the extrusion temperature. Last but not least the restart-point where the activated extruder starts printing again after toolchange can sometimes form a small blob, I guess because of some sliding-down of molten plastic inside the melt zone or some similar effect, maybe somehow connected with oozing...

Anyway, it would be good to be able to opt for using a small (r=5mm?) solid priming tower for each extruder that will always be printed first after toolchange and even when the extruder isn't used for the printed object in that layer. Without nozzle cooldown and reheating there's not much time lost for these "unneccessary toolchanges" (from the to-be-printed object's perspective), but all nozzles are used at least a little in every layer (anti-degeneration) - plus every extruder restart is performed on the priming-tower's island first and the object itself benefits from perfect quality like any further island in that layer.

I don't care much about the tiny amount of wasted material in this case, as the benefits and reliability of multi-extruder-prints would outbalance the downsides I think.

The reason why I don't really like the currently used skirt-for-priming idea is the poor reliability when restarting a potentially oozed nozzle. That thin skirt wall suffers really fast from bad flow restart, while a priming tower cylinder could be printed with like 2 or 3 perimeters where the chances are great that finally the outermost perimeter will come out fine, ensuring a solid and reliable tower geometrie all way up. Perhaps in this case "printing infill before perimeters" might also be a good choice, so the priming would be done in the infill and lack of extrusion on restart doesn't affect the tower geometry for later layers.

Furthermore the current skirt from ooze prevention feature always surrounds the whole object which can be quite a bit with large prints. I'd better like the material waste to be only dependend on the printed z-height, independend from the print size. Sure, the relation would be worst for very small prints, but really good for highly productive use of the full build surface..

Does anyone aggree?

**Comment by tjmustard** [comment]
I agree 100%. The print towers would be an ideal solution. I tried to hack this in with a tower of my own with support around it to force what you described. But I could not reliably assume the tower would be printed first to purge the nozzles.

Also, I will be adopting your method immediately.

**Comment by jonaskuehling** [comment]
Yeah  @tjmustard that's exactly the point, ensuring that those tower will be printed first is the major problem at the moment that prohibits an easy workaround by manually adding cylinders of say 1mm height, scaling them in z-height up to the size of the printed object as needed.

Btw., since this thread started with a slightly different topic (and a while back actually), should I write a new separate feature request for this particular "priming towers" thing, @alexrj ?

**Comment by tjmustard** [comment]
I think so...

**Comment by RepRapMe** [comment]
Primetowers - a temporary workaround

I have found that when using Repetier Host with Slic3r 1.1.7 it is possible to slice two amf files so that for each layer there is one object group that is printed be fore the other. How this is done in code is still a mystery to me but in Repetier Host V1.0.6 it works as follows:

 1. First add your desired amf object file using the encircled plus symbol from the right pane
 2. Next add “primetower.amf” and scale it in the Z-direction to fit the object from step 1
 3. Verify that the primetower is located behind the object to be printed as seen from View → Front View

It seems to me that the key to making this work is in step 3.
I had a suspicion that the magic is performed in the command line from Repetier Host to Slic3r but I have not been successful in acquiring this...

Anyway, this workflow seems to work consistently, so as a developer I would take a look at how Repetier Host handles its requests to Slic3r, the solution to making primetowers within Slic3r just might be a no-brainer...

**Comment by Nohtal** [comment]
Fyi KISSlicer had priming towers. I found this out last year and never looked back.
Thanks,
Nohtal
On Thu, Mar 12, 2015 at 6:40 AM, RepRapMe <notifications@github.com> wrote:Primetowers - a temporary workaround

I have found that when using Repetier Host with Slic3r 1.1.7 it is possible to slice two amf files so that for each layer there is one object group that is printed be fore the other. How this is done in code is still a mystery to me but in Repetier Host V1.0.6 it works as follows:


First add your desired amf object file using the encircled plus symbol from the right pane
Next add “primetower.amf” and scale it in the Z-direction to fit the object from step 1
Verify that the primetower is located behind the object to be printed as seen from View → Front View


It seems to me that the key to making this work is in step 3.
I had a suspicion that the magic is performed in the command line from Repetier Host to Slic3r but I have not been successful in acquiring this...

Anyway, this workflow seems to work consistently, so as a developer I would take a look at how Repetier Host handles its requests to Slic3r, the solution to making primetowers within Slic3r just might be a no-brainer...

**Comment by SystemsGuy** [comment]
Cura, KISS, and S3D all support priming towers, and as more "single nozzle, dual feed" heads come on the market, the more important the slicer supporting prime and purge becomes.

**Comment by xoan** [comment]
You have a «Tool change G-code» under «Printer Settings → Custom G-code» to
inject any kind of movement you want. I think it should be useful enough.

On Thu, Apr 9, 2015 at 10:41 PM, SystemsGuy <notifications@github.com>
wrote:

> Cura, KISS, and S3D all support priming towers, and as more "single
> nozzle, dual feed" heads come on the market, the more important the slicer
> supporting prime and purge becomes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexrj/Slic3r/issues/1780#issuecomment-91350657>.
>



-- 
Xoan Sampaiño [xoan@twitter|vimeo|flickr|delicious]

 /\  Document Freedom Day - Liberate your documents
_\/` http://documentfreedom.org/ - March 25th, 2015

**Comment by SystemsGuy** [comment]
Thanks Xoan - would love to see some suggest gcode to purge a triple feed, single nozzle hotend on tool changes.

**Comment by xoan** [comment]
@SystemsGuy http://deltaprinter.co.za/tri-colour/index.html

**Comment by SystemsGuy** [comment]
Thanks Xoan - got one that works if your printhead is not able to move outside the print area to a "purge" area?
