### ISSUE TITLE
Feature request - Adjust layer heights based on Z step quanta

### ISSUE THREAD

**Issue by Lodran** [alexrj/Slic3r#1827]
In order to avoid banding in prints (particularly on printers like Up! which have belt driven Z), its necessary to adjust the layer height so that it aligns to the printer's Z axis step resolution.

If slic3r knew what the Z step resolution was, it could automatically adjust layer heights or flow rates to match the printer's characteristics.

**Comment by alexrj** [comment]
I implemented this now.

**Comment by platsch** [comment]
@alexrj @lordofhyphens I just tested the feature implemented in https://github.com/alexrj/Slic3r/commit/53fee674897adcc65c0514464865ef679543367b and have two remarks:

- what does this factor 4? is it motivated by @Lodran s [comment](https://github.com/alexrj/Slic3r/issues/1827#issuecomment-37884004)? I think it leads to unpredictable behavior, e.g: if I use a `z_steps_per_mm` of 0.1 and a layer_height of 0.3, I would expect no correction since 0.3 is a multiple of 0.1, but Slic3r corrects the layer_height to 0.4...

- I've never experienced serious microstepping problems so I'm not sure if it is an issue, but with your solution a first_layer_height or raft setting can lead to a situation where no layer is matched (e.g. a first_layer_height of 0.25 in my example would never meet the full step). The motor would be equally off of the full step for each layer, but is that the idea? Maybe doing a simple modulo after computing the layer height vector would be a better solution? Drawback is aliasing effects if a small error accumulates over a few layers until it causes a +- extra step.

**Comment by Lodran** [comment]
@platsch

• the factor of 4 is a result of @nophead's input, early in the thread.

• It doesn't have to hit full steps.  The goal here is repeatability - as long as the carriage moves exactly (quanta) mm each layer, that's what we're after.

**Comment by platsch** [comment]
@Lodran thx for the explanation, I overlooked @nophead's statement. Anyway, I still think it not transparent for the user and should be at least stated in the tooltip.

**Comment by nophead** [comment]
On machines with lead screws you have plenty of excess Z resolution, so you can afford to throw a lot away for better accuracy by avoiding part step positions. On a machine with a belt driven Z axis you can't and ironically that is where errors in microstepping or coil asymmetries are likely to be noticeable.
