### ISSUE TITLE
XS test failing when compiling on Debian Wheezy because of old GCC version (4.7.2)

### ISSUE THREAD

**Issue by ledvinap** [alexrj/Slic3r#1965]
there seems to be some problem in trapezoid code in master.

```
    my $expolygon = Slic3r::ExPolygon->new($square);
    my $polygons = $expolygon->get_trapezoids(PI/2);
    is scalar(@$polygons), 1, 'correct number of trapezoids returned'; 
```

get_trapezoids returns empty list. Tracing the code everything is fine until passing polygon to boost::polygon::get_trapezoids() call, but this function returns empty list.

maybe assign is problem after `assign(ps, polygon_set);` : 

```
(gdb) p polygon_set
$2 = std::vector of length 1, capacity 1 = {{contour = {<Slic3r::MultiPoint> = {_vptr.MultiPoint = 0x7ffff69e86d0, points = std::vector of length 4, capacity 4 = {{x = 100, y = 100}, {x = 200, y = 100}, {x = 200, y = 200}, {x = 100, y = 200}}}, <No data fields>}, holes = std::vector of length 0, capacity 0}}
(gdb) p ps
$3 = {data_ = std::vector of length 1, capacity 1 = {{first = {first = {coords_ = {100, 100}}, second = {coords_ = {100, 200}}}, second = 1}}, dirty_ = true, unsorted_ = true, is_45_ = true}
```

The template magic in boost is out of my reach ... 
testing on debian  stable, 

```
cc --verison
cc (Debian 4.7.2-5) 4.7.2
```

**Comment by llluis** [comment]
Sorry for digging old issue here, but I'm building a fresh new install with:
- Windows 7 64bits, 
- strawberry-perl-5.22.0.1-64bit-portable, 
- gcc (x86_64-posix-sjlj, built by strawberryperl.com project) 4.9.2
- master https://github.com/alexrj/Slic3r/commit/6ac79e3ed6bf903edf45b52ee6fd68c1b0b54a9d

and I get an error (non-blocking) because of this fix (command not found in french):

    Running Build.PL
    Configuring F:/Software/Slic3r-master/xs ... 'cc' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

While this has no impact in my build, maybe we need a cleanup here?
