### ISSUE TITLE
Feature Request : Internal brim for Spiral Vase

### ISSUE THREAD

**Issue by traveltrousers** [alexrj/Slic3r#2026]
Having a brim on the inside and outside would help bed adhesion 100% and is easy to implement.

**Comment by queglay** [comment]
There are other circumstances where this would be very useful.  yes they can be difficult to remove on the interior but on some objects that extra adhesion is really necessary.

For example this large object with ports in it - even if i make a custom interior brim in the bottom to deal with adhesion in the model, it's no good because the curvature is not correct to be able to easily remove the interior brim.  just using abs juice is not enough in this situation to print this part without the corners warping upwards.

An interior brim option in this case would solve the problem.  This is not just a special case like the vase may be with adhesion, other parts with large holes near the corners could have these issues too.

<img width="1498" alt="screen shot 2015-09-05 at 7 37 36 pm" src="https://cloud.githubusercontent.com/assets/4046493/9698739/fb89c35c-5406-11e5-8324-681ad7f8adf9.png">

**Comment by kitchung** [comment]
I'd like to see this as well. I have a model where support inside an object kept getting knocked off the bed but the support outside stayed on since they were on the brim.

**Comment by sjlynch** [comment]
+1

**Comment by alexrj** [comment]
Done! A new Interior Brim option is now available.

**Comment by bubnikv** [comment]
+1
