### ISSUE TITLE
seam_position = random does not work with a single perimeter

### ISSUE THREAD

**Issue by alranel** [alexrj/Slic3r#2179]
This happens also when multiple perimeters are configured but only one is generated, as in both cases EXTRL_ROLE_CONTOUR_INTERNAL_PERIMETER is missing.

**Comment by DeepSOIC** [comment]
Hi! This problem seems to be happening in 1.2.9. I tried slicing a one-extrusion-wide walled cylinder, and Slic3r put the seam in an aligned manner instead of random.
; avoid_crossing_perimeters = 0
; bed_shape = 0x0,185x0,185x160,0x160
; bed_temperature = 110
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 0
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_gcode = M104 S0 ; turn off temperature\nM84     ; disable motors
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.95,0.95
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF;#FFFFFF
; filament_diameter = 1.75,1.75
; first_layer_acceleration = 0
; first_layer_bed_temperature = 130
; first_layer_extrusion_width = 0.38
; first_layer_speed = 70%
; first_layer_temperature = 250,250
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 0
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 0
; min_print_speed = 7
; min_skirt_length = 20
; notes = 
; nozzle_diameter = 0.3,0.3
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_layer_change = 0,0
; retract_length = 1.5,1.5
; retract_length_toolchange = 1.5,1.5
; retract_lift = 1,0.2
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 300,300
; skirt_distance = 0.5
; skirt_height = 1
; skirts = 8
; slowdown_below_layer_time = 7
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = 
; temperature = 240,240
; threads = 2
; toolchange_gcode = 
; travel_speed = 200
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0,0
; z_offset = 0
; dont_support_bridges = 0
; extrusion_width = 0.38
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.125
; raft_layers = 0
; seam_position = random
; support_material = 0
; support_material_angle = 45
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.7
; support_material_interface_extruder = 1
; support_material_interface_layers = 1
; support_material_interface_spacing = 0.5
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 0.5
; support_material_speed = 40
; support_material_threshold = 45
; xy_size_compensation = 0
; bottom_solid_layers = 1
; bridge_flow_ratio = 1
; bridge_speed = 40
; external_fill_pattern = concentric
; external_perimeter_extrusion_width = 0.38
; external_perimeter_speed = 100%
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 0
; fill_density = 25%
; fill_pattern = rectilinear
; gap_fill_speed = 40
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.38
; infill_overlap = 0.05
; infill_speed = 40
; overhangs = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.38
; perimeter_speed = 40
; perimeters = 3
; small_perimeter_speed = 40
; solid_infill_below_area = 5
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 30
; thin_walls = 1
; top_infill_extrusion_width = 0.6
; top_solid_infill_speed = 30
; top_solid_layers = 0
STL file: see https://drive.google.com/file/d/0B9lBm-SSD5KSa05VeDBKOVc1c3M/view?usp=sharing
