### ISSUE TITLE
[feature request] info about material used upfront 

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#2250]
It would be nice if 'filament used' info would be displayed somehwere after 'export gcode'.

data is there, after one opens up file, total filament lenght and volume is displayed at the very bottom.
it is just very inconvinient to open up large gcode file in text editor and scroll to the bottom (btw. noticed openscad does this job faster than leafpad and nano )

**Comment by bobemoe** [comment]
Additionally, it would be nice to see the value after slicing has completed rather than after gcode export, so that the effect of changes to settings can be seen instantly, rather than only after export.

I have created the following bash script that I've added to the post-processing scripts that extracts the filament used line and shows it in a zenity popup dialog:

```
#/!bin/bash
/usr/bin/zenity --info --text "`grep used $1`"
```

But I have to export gcode each time I change settings for it to execute. It would be much more useful if it was executed at the end of the slicing process, imposable of course as it depends on the existence of the exported gcode file to extract the value from, but if this is being added as a feature this would be worth bearing in mind.  There is even a nice space for an extra value in the 'info' section under the platter tab.

Thanks all :)
