### ISSUE TITLE
Feature request.  Adjustable distance from support material.

### ISSUE THREAD

**Issue by octo777** [alexrj/Slic3r#2272]
Can we add the ability to control how close the support material comes to the part in X/Y and Z?

I noticed that the part material stays about 6 to 8 layers away from the support underneath.
On large radii moving in the Z axis,  the support pulls away from the radius nicely, but it is many layers too soon. The part doesn’t catch up for about 8 layers time and by then it is 1.6 mm above the support material. 
The flat overhang started getting printed about 6 layers after the support stopped. 

Thanks,

Jeremy

**Comment by alexrj** [comment]
I added an option for vertical distance between object and support. Regarding horizontal distance, a few issues were fixed that caused too much adhesion. I think that horizontal distance shouldn't be configurable because the software can decide a smart distance. Anyway, there's another issue here in GitHub specifically about XY distance.
