### ISSUE TITLE
Gcode toolpathing produces weak parts, no infill

### ISSUE THREAD

**Issue by TTN-** [alexrj/Slic3r#2346]
git rev-parse HEAD
eab09866cbfe508b8e002f6f6a5ecd98e1cdea6f
Ubuntu 14.04 64bit
Slic3r 1.2.1
Built from source using perl v5.18.2 from ubuntu repositories, as recomended on slic3r.org/download

Steps to reproduce issue:
load escapement_wheel.stl in slic3r.
Export as gcode.
Load gcode with gcode viewer.
Note how the gcode is suboptimal, and how infill is not generated correctly (there is none, but 100% rectilinear infill is selected in settings).
Gcode generated using Cura reveals very different toolpathing, which is much stronger (I've printed both).

Expected result:
Toolpathing that connects parts strongly and has infill.

Stl model: http://www.thingiverse.com/download:591232

Slic3r config.ini: http://pastebin.com/pE3BgfL2

Generated with Slic3r:
![screenshot from 2014-11-09 09 02 29](https://cloud.githubusercontent.com/assets/6019316/4965439/4a2cca52-67f1-11e4-8687-31942fbdd080.png)

Generated with Cura:
![screenshot from 2014-11-09 09 01 53](https://cloud.githubusercontent.com/assets/6019316/4965440/4fece882-67f1-11e4-8925-0f3db94ba3c7.png)

**Comment by zapta** [comment]
This problem is very real, to the point that I switched to Cura which does proper infill between the thin vertical layers. A test model is available here http://www.thingiverse.com/thing:642051 .All the three walls in the center did not have infill and were very soft. Had the same problem with this model http://www.thingiverse.com/thing:168437 which prints vertically, it was flaky like paper because of the missing infill. I wouldn't dismiss this problem that easily, it's serious.
