### ISSUE TITLE
'extra perimeters when needed' always enforces minimum 2 perimeters

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#2395]
Even on perfectly 90 degree perpendicular to surface objects, without infill 'extra perimeters when needed' does enforce minimum of 2 perimeters. disabling this option makes proper 1 perimeter part.

**Comment by curiouspl2** [comment]
just tried 1.2.4 and it's also affected.
something is generally wrong about angle detection logic , because if you slice 25 to 40 fan adapter (rotated properly ofc) from here :
http://www.thingiverse.com/thing:21112/#files

you get 1 perimeter result gcode file, even though it is not perpendicular to the table.
it has not very steep angle, but still it means not whole top layer lies on bottom layer, so 
1)extrusion width is different  - extrudate is not spreaded 100% like on layer directly below 
2)bonding is very weak 
3)with just a bit more steep angle effects of 1 and 2 will eventually grow enough to create holes. 
'create extra perimeters when needed' theoretically should mediate that but there is no angle threshold.

extrusion compensation (the more angle the more extrudate) could help to gap this problem, and would also solve 
https://github.com/alexrj/Slic3r/issues/2313

**Comment by alexrj** [comment]
Good catch there. I reimplemented the detection algorithm for extra perimeters. Your test case now has the extra perimeters in a very limited number of cases, which makes sense. Further testing will tell us if this implementation is correct.
(The geometric definition of the extra perimeters logic is actually tricky since it's ambiguous)
