### ISSUE TITLE
Installing Slic3r on Raspberry Pi (raspbian) Fails

### ISSUE THREAD

**Issue by Analogreality** [alexrj/Slic3r#2402]
I'm attempting to follow the steps necessary to build Slic3r on a Raspberry Pi (using raspbian).

Invoking 'perl Build.PL' results in a long compilation, followed by a fatal error:

Can't locate Slic3r/XS.pm in @INC (@INC contains: /home/pi/slicertest/Slic3r/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /home/pi/slicertest/Slic3r/lib/Slic3r.pm line 38.
BEGIN failed--compilation aborted at /home/pi/slicertest/Slic3r/lib/Slic3r.pm line 38.
Compilation failed in require at ./slic3r.pl line 15.
BEGIN failed--compilation aborted at ./slic3r.pl line 15.

All attempts at searching for this type of issue on Google seem to show other people's attempts.. but that was in 2012.

**Comment by mojoTheReplicator** [comment]
Hi,

I had the same problem that XS.c could not be compiled. 

At my rasbpi system was due to too less memory - i saw it during the build process (using the "top" command) that even the swap space was fully used.

For me it helped to increase the swap space from 100 MB to 500 MB through editing the file

 /etc/dphys-swapfile

and altering the line 

CONF_SWAPSIZE=100

to 

CONF_SWAPSIZE=500

after this remount the swap with

sudo /etc/init.d/dphys-swapfile stop
sudo /etc/init.d/dphys-swapfile start

and rerun the build process.

Good luck - and let me know if you succeeded! - If yes we should post this possible solution on the site http://entropyprojects.blogspot.co.at/2012/08/slic3r-on-raspberry-pi.html

**Comment by lordofhyphens** [comment]
This *looks* likes it's resolved, closing. Please reopen if it isn't.

**Comment by ChristophSchranz** [comment]
This topic is old, but I have not found any other Slic3r release for the Raspberry Pi.
It is version from 1.3.1-dev and works for me on Stretch
https://github.com/iot-salzburg/Slic3r/releases
