### ISSUE TITLE
Skirt and brim order reversed

### ISSUE THREAD

**Issue by gaby64** [alexrj/Slic3r#2405]
when i updated to 1.2.1 the brim was inside the skirt
with no way to adjust the brim height, its just breaks from the part when the part corner lifts

**Comment by gaby64** [comment]
my point was that the skirt and brim order was reversed

the brim is layer height, so at 0.0625mm layers, it breaks easily
normally the brim would surround the skirt and open surfaces

cross-section, i expect this
__brim__---skirt---|||||||part|||||||---skirt---__brim__
not
---skirt---__brim__|||||||part|||||||__brim__---skirt---

i have not had the chance to test any following release due to filament problems and broken extruder


can anyone confirm that this is fixed?

**Comment by a4jp-com** [comment]
Hi Gaby 64. I know it is a bit confusing but the skirt should be on the outside, shouldn't it? Brim kind of means hat brim, doesn't it? And skirt means skirting edge as far as I know.

Maybe different words would make more sense as a skirt and brim kind of mean the same thing in English.

Brim
1.the upper edge of anything hollow; rim; brink:
the brim of a cup.
2.a projecting edge:
the brim of a hat.
3.margin.

Skirt
7. Usually, skirts. the bordering, marginal, or outlying part of a place, group, etc.; the outskirts.

**Comment by gaby64** [comment]
im interested in function, not semantics

from experience the brim is applied to every open edge, including the contour



the skirt is useless in keeping the part from warping if it is separated from the part by a fragile brim

**Comment by whosawhatsis** [comment]
@gaby64 Are you perhaps confusing the two terms? Brim is the one that connects to the print and helps hold it down. Skirt is not supposed to be connected to the print at all, it's just an outline surrounding the print, and there is supposed to be at least 1mm gap between the skirt and anything else.

**Comment by gaby64** [comment]
@whosawhatsis 

i cant specify how many layers the brim is, so it cant work at low layer heights

but my main point is that the behavior of the software changed from 1.1.7 to 1.2.1
which did not work for me.

**Comment by whosawhatsis** [comment]
Ah, so you've been using the skirt for the purpose that a brim is intended for with multiple layers. Have you tried using the First layer height and first layer extrusion width? That will give you better platform adhesion and less sensitivity to a platform that is not perfectly tram or flat, and will also make both your brim thicker so that it can serve its intended function.

It sounds like the behavior you were taking advantage of in the older version was a bug, that has since been fixed to work the way it was always intended to, and the way it has to work for those features to have their intended respective functions.

It sounds like what you should really be requesting is an option for multi-layer brims, but I think you'll find that unnecessary if you increase your first layer height and extrusion width as I suggested.

**Comment by a4jp-com** [comment]
Multi layer brims would be useful if we want to have a skirt at the same time. Also when we want to keep the brims and use them as part of the design. I just use the skirt to do this though. Set the distance from the model to 0mm then increase the number of layers and loops.

**Comment by gaby64** [comment]
@whosawhatsis 

i missed the first layer height setting
