### ISSUE TITLE
Software backlash compensation

### ISSUE THREAD

**Issue by printrboy** [alexrj/Slic3r#2431]
Backlash is a problem many 3d printers can suffer from.
To get rid of or lessen the effect of backlash people spend money upgrading their printers, such as replacing rods, belts, pulleys, higher torque motors, even frames for stronger frames, spending hours on calibrating and some don't manage to get rid of it even after doing all of this it seems (example links below).
I even shorted my motherboard fixing the VREFs to improve backlash artifacts.

Software backlash compensation is compensating for the missed "steps" caused by backlash via software.
Simplest way to think about it is since you don't want something to print deformed, you deform the 3d model "the opposite way" in software before printing so it comes out as expected.

Examples of this issue:
Printrbot: http://www.printrbottalk.com/forum/viewtopic.php?f=20&t=3510
Solidoodle: http://www.soliforum.com/topic/8199/odd-circle-test-results/
Replicator: https://groups.google.com/forum/#!topic/makerbot/t37iS3MdAqQ
Prusa: http://forums.reprap.org/read.php?4,268013
https://groups.google.com/forum/#!topic/solidoodle/MNnym1MC94Y
http://3dprintboard.com/showthread.php?584-Circles-aren-t-printing-like-they-should-be
http://forums.reprap.org/read.php?151,71788,page=1

Skienforge has something like this though I've never tried it: http://fabmetheus.crsndoo.com/wiki/index.php/Skeinforge_Lash

Someone was working on code for doing this in Marlin firmware, but this never got completed and never merged to the official marlin firmware.
https://github.com/ozadr1an/Solidoodle-Marlin_v1

Here's an example of a software backlash compensation via the above custom firmware:
<a href="http://imgur.com/i2W4OR5"><img src="http://i.imgur.com/i2W4OR5.png" title="source: imgur.com" /></a>
Not perfect but way better and just using a close number.

If Slic3r had such a feature, it would save lot of people time and money on a hardware fix and a solution for those who don't have the technical knowledge to modify their printers.

**Comment by lukie80** [comment]
Just wanted to add some relevant information. Implementing backlash compensation in Slic3r or by a post-processing script for the gcode does solve the problem theoretically but introduces other bad issues.

I wrote a simple compensation script for the gcode and results are far from ideal. The problem is, that the compensation-movements are evaluated as real movements by the firmware which causes unnecessary deceleration and thus degrades print quality. Backlash compensation must be performed in firmware and in particular after the movement-planner: Backlash-compensation movements are nearly load-free and do not require acceleration-planning. 

So the ideal solution would be to modify the firmware after the movement-planner and before the stepper-driving. This is not a trivial task I assume. Repetier Firmware has a backlash compensation but it is unfortunately implemented before the planner.

**Comment by platsch** [comment]
Fully agree with @lukie80, just want to add: from my experience, backlash compensation can improve the printing quality even on high-end industrial hardware when you are going for really accurate results.
Additional to the problem of correctly implementing the compensation, it is not trivial to correctly calibrate the actual backlash for a machine.
