### ISSUE TITLE
[Feature Request] Overhang support concept

### ISSUE THREAD

**Issue by Laura3** [alexrj/Slic3r#2469]
I love how much slic3r has improved in the last release. 
Especially the preview window, I used to export and import to check what the gcode was like.
I feel the workflow is much improved this way. Thanks @alexrj 

So I thought to myself, looking at my printed owl's wee overhangs, maybe that's something that could be improved. I remembered [Werner Berry's video of his yoda prints,](https://www.youtube.com/watch?v=KUIbMnqFstk) of how the printed yoda ears were supported.

That might be an idea to play around with? To create little stringy supports off the edge of objects to support overhangs?

Some video stills from Werner's video:

![vlcsnap-2015-01-01-09h07m11s227](https://cloud.githubusercontent.com/assets/6019316/5590279/fce7bc6a-9195-11e4-8b7c-857bedaa9937.png)
![vlcsnap-2015-01-01-09h07m21s79](https://cloud.githubusercontent.com/assets/6019316/5590278/fc9b3ac0-9195-11e4-867d-84781284da31.png)
![vlcsnap-2015-01-01-09h12m51s46](https://cloud.githubusercontent.com/assets/6019316/5590301/62616b18-9196-11e4-98b4-bbe0640344f0.png)

**Comment by DwayneS** [comment]
I believe what you see is ooze, not an intentional structure. Those threads are also too weak to support filament. If you want to play with such structures they can be generated by MeshMixer which can be downloaded for free. It adds them to your STL which can then be slicer with Slic3r. Current support material generation works quite well, other than a somewhat large gap (adjustable gap would be nice and easy to implement).

**Comment by Laura3** [comment]
I see your point. I'll close this issue then.
