### ISSUE TITLE
Contributors cut off in About dialog

### ISSUE THREAD

**Issue by blue-ice** [alexrj/Slic3r#2476]
Slic3r version 1.1.7
Lubuntu Trusty 14.04 LTS

Any config file can be used. The expected result is that all contributor names should be visible in the About dialog. Instead, only a few can be viewed, and the rest are cut off. The window cannot be resized.

![2015-01-01-150757_634x311_scrot](https://cloud.githubusercontent.com/assets/7453952/5593396/68f8c2b4-91c8-11e4-8e7e-b3d49e237747.png)

**Comment by walruses** [comment]
Same issue in 1.2.4 on windows 7

**Comment by alexrj** [comment]
Thank you! I increased the window height.

**Comment by xoan** [comment]
This issue is happing again.

![captura de pantalla_2017-05-19_18-04-09](https://cloud.githubusercontent.com/assets/288246/26256712/20957f46-3cbe-11e7-8b55-a510da3a61a8.png)

It is a low priority issue, and it will be probably fixed when GUI finishing porting from Perl to C++, so this comment it is only to taking this into account, and to look for a better way to set window size depending on content.
