### ISSUE TITLE
unideal bridge direction

### ISSUE THREAD

**Issue by vapetrov** [alexrj/Slic3r#2477]
version 1.2.4 64 bit

model:https://www.dropbox.com/s/qxprwbjgljlvx0k/lego.stl
![capture](https://cloud.githubusercontent.com/assets/7529600/5593416/68968346-91d3-11e4-8236-e2ff39e0d017.PNG)
As you can see, slic3r attempts to bridge lengthwise. Although this technically works, if the bridge direction was rotated 90 degrees, the length of the bridge would be much shorter.

Ideally, there should be an option to override bridge direction.

**Comment by harriv** [comment]
Ideally, Slic3r would automatically find the optimal solution :)

**Comment by blue-ice** [comment]
Windows 7?

**Comment by walruses** [comment]
I'm getting identical results in Win 7 and XUbuntu.

**Comment by alexrj** [comment]
Good test case. The current logic should actually suggest the other direction: Slic3r chooses the direction that has most coverage and shortest max line length - in this case both directions have equal coverage, so it shouldn't be choosing this one. However coverage of angle 0° results slightly greater because of the way it is computed.
I think I should find a more robust algorithm for computing coverage/visibility.

**Comment by alexrj** [comment]
Hm, I think I don't have the STL file anymore. I'll check on another computer.

**Comment by alexrj** [comment]
[lego.stl.zip](https://github.com/alexrj/Slic3r/files/872073/lego.stl.zip)

**Comment by alexrj** [comment]
This was an excellent test case. I improved the bridge detection code and also applied one more algorithm to handle bridges covering pillars. A regression test was added to the test suite.
