### ISSUE TITLE
Adjacent bridge areas not being combined

### ISSUE THREAD

**Issue by merkur2k** [alexrj/Slic3r#2506]
I have a case where I have two bridge areas close enough to each other that they overlap. Instead of combining it into one bridge, it is doing them one at a time which leaves the edge of one over open air causing it to fail.
Slic3r 1.2.4 Windows 7 x64.
Here is the layer below the bridge:
![slic3r-1](https://cloud.githubusercontent.com/assets/3111724/5648398/1127c20e-9643-11e4-95d0-bf76cc775480.PNG)
And the bridge layer:
![slic3r-2](https://cloud.githubusercontent.com/assets/3111724/5648397/1127afb2-9643-11e4-8651-4b2acc66f42f.PNG)

**Comment by mkurc1234** [comment]
I have noticed this issue is present still in 1.2.5. I had tried to print a T shaped object with my own support structure and this is what i got:

Layer before bridging:
![1](https://cloud.githubusercontent.com/assets/7130520/5691142/730a308e-98b8-11e4-923f-1d494b522ca0.png)

Bridging layer:
![2](https://cloud.githubusercontent.com/assets/7130520/5691143/7ba01e98-98b8-11e4-8465-ea66aa21b595.png)
The bridge structure should span the whole layer surface while it changes abruptly not even on perimeter boundary but in mid air.

Layer above bridges:
![3](https://cloud.githubusercontent.com/assets/7130520/5691149/9ef1f902-98b8-11e4-9d3f-66507c936573.png)

BR,
Maciej

**Comment by harriv** [comment]
Please add information about your settings and STL files, otherwise it's very hard to find out what's wrong. See the guidelines: https://github.com/alexrj/Slic3r/blob/master/CONTRIBUTING.md

**Comment by mkurc1234** [comment]
Here it is: https://www.dropbox.com/sh/9je1p1o7ku1qao4/AACMZI6zYRfJ51cV6oKWF1ADa?dl=0

**Comment by lordofhyphens** [comment]
The testcase is a dead link, and I believe this has been fixed in the intervening time. 

Will reopen if a test case appears (please upload here according to the directions at https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)
