### ISSUE TITLE
1.2.5 exp - exporting takes a lot of time when "avoid crossing perimeters" is checked

### ISSUE THREAD

**Issue by gege2b** [alexrj/Slic3r#2538]
Hi there
as usual : slic3r 1.2.5 exp on Win7 x64

May be it's not bug, may be it's only esthetics, I don't know. In this case sorry for this report.

It works with any STL, but here is the one I'm using : https://dl.dropboxusercontent.com/u/34934879/bastia%20logo%20creux%2010x10.STL

The config is not important, except for "avoid crossing perimeters". When checked, Slic3r takes a LOT of time on the "exporting gcode..." status.

I know this option is time consuming, but I trought this should occurs on the "generating perimeters" phase, not on the exporting one

cheers

**Comment by dexy31337** [comment]
I've noticed, that "exporting gcode" phase is most time-consuming for difficult models, especially with small layers (0.1mm). While slicing is multithreaded, I believe that expoting g-code is sequential as file is written line-by-line. So, due to great amount of lines (hundreds of thousands), it is normal, that exporting takes some time.
Same with "avoid crossing perimeters", as it generates a lot of extra movement commands.

**Comment by lordofhyphens** [comment]
Try current 1.3.0-dev (see link on main readme), reopen if there are still issues. Avoid crossing perimeters is a bottleneck in the code output.
