### ISSUE TITLE
Clarify install instructions for linux

### ISSUE THREAD

**Issue by prof-braino** [alexrj/Slic3r#2650]
On http://slic3r.org/download The instructions for linux say: Click on your operating system to download the precompiled packages.  But they do not say what to do next. I ended up using the 
https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux
which ended up crashing on my system (mentioned in a separate issue).

My suggestion is to add specific steps to Option 1 for linux:
- Download the latest stable archive (typically to ~/Downloads by default)
- Extract the archive in place (Extract Here) as this is temporary
- Move the extracted Slic3r folder to Home directory
- locate the executable ~/Slic3r/bin/slic3r
- On first execution Slic3r will ask about the use's equipment, and set up configuration files which can be modified.

Also, the Slic3r Manual install instructions at http://manual.slic3r.org/getting-slic3r/getting-slic3r#installing say: 
<<<
Extract the archive to a folder of your choosing. Either:

    Start Slic3r directly by running the Slic3r executable, found in the bin directory, or

    Install Slic3r by running the do-install executable, also found in the bin folder.

The archive file may then be deleted.
>>>
However, the possible option depends on the install option; there is no /bin executable in the git method, and there is no install or setup.py script in the precompiled download.   Each option should be presented clearly and separately. This would really help new fols, which is the target audience. 

Cheers!

**Comment by lordofhyphens** [comment]
If you use linux, you should be able to work out what a ./bin directory is for. 

Otherwise you should use your distribution's packages (or spend the hour or so learning how to make one for yourself, commonly by taking the package sources from your distribution and overwriting the source code with the current version from git).

Debian 8 has a working package for 64-bit (see my fork of Slic3r), there's a Ubuntu package available at prusa3d.com
