### ISSUE TITLE
Low graphics quality on Mac with Retina display

### ISSUE THREAD

**Issue by kevinguibert** [alexrj/Slic3r#2888]
Hi,

I'm a great fan of slic3r.

Recently, i changed my old Mac to a MacBook Pro with a Retina display.
When i installed slicer 1.1.7, i noticed that the GUI was in low graphics quality.

After some search over the web, i found that the app "Retinizer" was able to correct that and allow slic3r to have a high graphic quality on retina display (with a simple drag and drop of slic3r.app in the main window of the program).

I'm not good in programming but it might be really interesting for the development of Slic3r to use this app.

Best Regards

**Comment by alexrj** [comment]
Can you post a screenshot of how it looks, please?
I don't have access to a Retina display.

Anyway, the appearance of the GUI is tied to the framework we use (wxWidgets), so it's something that should be reported to them as it's not in Slic3r's codebase.

You might also want to try a recent version like 1.2.7 which is nicer and is also compiled with a more recent version of wxWidgets.

**Comment by kevinguibert** [comment]
Hi Alex,

I'm really sorry by posting this here since you told me it comes from the framework, but i will be pleased if i can help you.

Here are 2 screenshots from 1.1.7 (number 1 : without Retinizer app, number 2 with). I will post you some screenshot from the 1.2.7 which is having the same "low graphics display" (number 3 without, number 4 with)

![1 - slic3r 1 1 7](https://cloud.githubusercontent.com/assets/4600475/8028820/cf219094-0db4-11e5-8f42-0022af777539.png)
![2 - slic3r 1 1 7](https://cloud.githubusercontent.com/assets/4600475/8028819/ceea71f4-0db4-11e5-8396-663da3ef0181.png)
![3 - slic3r 1 2 7](https://cloud.githubusercontent.com/assets/4600475/8028838/1f4e291a-0db5-11e5-9070-c27357f86914.png)
![4 - slic3r 1 2 7](https://cloud.githubusercontent.com/assets/4600475/8028837/1f283b7e-0db5-11e5-99e9-eedb540c2dbb.png)

**Comment by mikenew12** [comment]
I think this is partially resolved in the dev build already. Here's a screenshot of 1.2.7, and then the same shot in the dev build.
![screenshot 2015-06-07 23 50 57](https://cloud.githubusercontent.com/assets/522101/8029309/72c0acfc-0d70-11e5-879b-da6a3bbfb308.png)
![screenshot 2015-06-07 23 50 25](https://cloud.githubusercontent.com/assets/522101/8029313/783a09f8-0d70-11e5-9492-3c8e189a6d39.png)
The text and UI elements render at high resolution, but the icons don't. Obviously the icons aren't going to be high res unless there's also a @2x version included with the app. No idea if wxWidgets supports that or not.

**Comment by kevinguibert** [comment]
Indeed, it seems that the dev version of Slic3r resolved that "low graphics display" issue. 
And as you said, the better way to get high res. icons is to implement @2x images.

Seems that my issue wasn't really a big issue !

**Comment by alexrj** [comment]
Ouch, maybe I'm blind but I can't see any difference within each pair of screenshots you posted above!

Regarding the improvement that @mikenew12 mentions between 1.2.7 and dev (which I still fail to see from screenshots!) I think it's not a true change in Slic3r but a different behavior when you run a version which is compiled on another system (1.2.7, which I compile on OS X 10.6) and one compiled on your own system using native libraries.

(@kevinguibert, @2x is a CSS/web concept and does not apply to wxWidgets or GUI programming in general)
Unfortunately I have no Maverick or Retina to test or build on.

**Comment by kevinguibert** [comment]
well i didn't think straight on screenshots. 
The only way to see if it's high res. or not is having... a retina display...

2 solutions might be possible then : 
1/ Compiling Slic3r on Maverick to get high def GUI
2/ Add a note to users with a link to Retinizer, if they want/need a high def GUI on Mac w/ Retina display

**Comment by a4jp-com** [comment]
Can scalable vector images be used? I use them on my websites and don't have any scaling problems. I'm not sure how practical this solution is, but having something like wxWebKit embedded in your application and then using something like WebKit's SVG support to do the rendering if possible.

http://www.webkit.org/projects/svg/index.html

wxWebKit 
04/13/2013: This project is no longer under active development. Those considering embedding a WebKit browser in their wx application should consider embedding Chromium instead.

**Comment by mikenew12** [comment]
@alexrj 10.6 predates retina displays, so I'd imagine you're right; the difference is the build environment. Here's a couple blown-up screenshots so you can see the difference. 
![screenshot 2015-06-08 10 28 44](https://cloud.githubusercontent.com/assets/522101/8040948/8b975db2-0dc9-11e5-8bf5-4fb1703ea7e6.png)
![screenshot 2015-06-08 10 28 34](https://cloud.githubusercontent.com/assets/522101/8040950/8da65b8a-0dc9-11e5-8ad3-992f6bc95780.png)

You actually can see the difference on the previous screenshots if you zoom in, even without a retina screen (or HiDPI if you want avoid the marketing speak). Just look closely at the text.

Also, a quick test shows that @2x assets are handled properly by wxWidgets, at least when building on my 10.10.3 machine. The @2x is a web convention, but it's also what Apple uses on OS X and iOS. I quickly drew a new 'red x' icon at 32 x 32 rather than the 16 x 16 of the original and added it to the 'var' folder as 'cross@2x.png'. Building and running on my non-retina machine shows the original, while the retina machine shows the higher-res icon.
![screenshot 2015-06-08 10 23 28](https://cloud.githubusercontent.com/assets/522101/8041051/3e4064c2-0dca-11e5-9b53-f4e153841aae.png)
![screenshot 2015-06-08 10 22 05](https://cloud.githubusercontent.com/assets/522101/8041056/4109f006-0dca-11e5-8174-3d01666ee038.png)

Obviously this isn't a critical issue, but @kevinguibert is right, it really makes Slic3r much, much prettier on a retina mac. I do some OS X development, and I would be more than happy to package releases built against the latest SDK if you'd like. It would at least make the text and UI elements look better, and if you're able to get those icons at double resolution that would take care of everything.

**Comment by kevinguibert** [comment]
Well, @mikenew12 your cross is definitively a high definition icon on a HiDPI (i'm trying to fit in) display !
As you said, not a critical issue, but it looks really nice on a Macbook Retina display !

**Comment by alexrj** [comment]
I compile on 10.6 because that ensures Slic3r is compatible with older Macs. I'll think about possible solutions. All of them include finding a new set of icons that has 32x32 versions :)

**Comment by mikenew12** [comment]
You should be able to build on 10.10 and set your build target to 10.6. And yes, higher res icons would be great :)

**Comment by dragosmiron** [comment]
up

**Comment by dragosmiron** [comment]
i dont think anyone has a low res mac anymore.

**Comment by alexrj** [comment]
This should be fixed as of now. Get a fresh automated build at http://dl.slic3r.org/dev/mac/

**Comment by gabrielmulle** [comment]
Hey folks, I see this was closed as resolved in 2017. I just downloaded this software version 1.2.9 and the low resolution graphics is still a thing. Any ideas?

**Comment by michaelnew** [comment]
@gabrielmulle ...download the current release, not an old one?
