### ISSUE TITLE
[1.2.9-stable] weird overextrusions in thin walls area

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#3189]
Hello. try slicing "top" part of : 
http://www.thingiverse.com/thing:1077430/#files
with extrusion width settings : 
external perimeters = 0.7
infill = 0.7 

you should get something like : 
![thinwall_problem](https://cloud.githubusercontent.com/assets/6697487/12077825/f3ad7838-b1c4-11e5-8f48-ea43291c3127.jpg

width of overextruded mess seems to be proportional to extrusion width of infill. 

this is especially annoying when using scanned/sculpture objects where you cannot easily find all thin walls/correct them. note overextrusion varies from model to model due to some mysterious bug - sometimes it's even larger, making lot of mess. 

note : disabling thin wall detection makes problem 'disappear' though obviously thin walls collision checks are also gone .

**Comment by lordofhyphens** [comment]
Found a similar problem, seems related to the layer height.

![over_infill](https://cloud.githubusercontent.com/assets/31754/13902143/beb24abe-ee0a-11e5-8fcf-6fb9ab8bd775.png)
[overinfill.zip](https://github.com/alexrj/Slic3r/files/181103/overinfill.zip)

Setting the layer height to 0.1 instead of 0.05 causes the outer ring area to render as below:
![strange_underfill](https://cloud.githubusercontent.com/assets/31754/13902156/34bb3d06-ee0b-11e5-95ff-f47dd70a92c2.png)

**Comment by alexrj** [comment]
@curiouspl2, I tested your file with current master (1.3.0-dev) and the following command line options:
`--external-perimeter-extrusion-width 0.7 --infill-extrusion-width 0.7`

I get a clean result:
![schermata 2016-03-26 a 18 40 14](https://cloud.githubusercontent.com/assets/594957/14061539/8a20f318-f382-11e5-9302-e5cdab3b2657.png)

I also tested with current stable (1.2.10-dev) and I get this:
![schermata 2016-03-26 a 18 41 10](https://cloud.githubusercontent.com/assets/594957/14061540/9b161d7e-f382-11e5-84fc-b315c07cf013.png)

Do you have a chance to test with one of these git branches and confirm this is fixed?

@lordofhyphens, please let me know if yours is fixed as well now.

**Comment by lordofhyphens** [comment]
The thin gapfill has gone away (to be replaced by nothing), but the overextrusion screenshot was not gapfill; it was regular infill and that is still present in 9576973b578f0c39f8cbd73c225187ba65b6cef4.

**Comment by alexrj** [comment]
Thank you for testing @lordofhyphens

**Comment by lordofhyphens** [comment]
@alexrj it appears that the massive overfill on the infill that I noticed
occurs when thin wall detection is on, and it's definitely not gapfill
(gapfill speed is set to 0)

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
#3196 may be related to this, at least regarding the solid infill width being calculated incorrectly.

**Comment by alexrj** [comment]
@lordofhyphens, I tested your overinfill.zip file with current master and I confirm the issue is fixed:

![schermata 2016-12-21 alle 17 19 36](https://cloud.githubusercontent.com/assets/594957/21396836/d0c47094-c7a1-11e6-9ff8-d6644e32150f.png)
![schermata 2016-12-21 alle 17 22 51](https://cloud.githubusercontent.com/assets/594957/21396917/22934d82-c7a2-11e6-9df4-fe4de680fce0.png)

When enabling gap fill:
![schermata 2016-12-21 alle 17 23 35](https://cloud.githubusercontent.com/assets/594957/21396944/3931f5d4-c7a2-11e6-9fdb-eb04e316d7ef.png)

**Comment by lordofhyphens** [comment]
Excellent. Any idea what this was (other than perhaps the issue with that function not being idempotent)?

**Comment by alexrj** [comment]
I think that was the issue, because those extrusions were huge and that issue caused width to grow at each cycle. Other issues related to extra gap fill had other overlaps but not such a huge width...
