### ISSUE TITLE
Solid fill is not calculated correctly

### ISSUE THREAD

**Issue by mkubi** [alexrj/Slic3r#3210]
![slic3r_correct](https://cloud.githubusercontent.com/assets/11003333/12387459/eea43958-bdcc-11e5-82b4-04d578c7c9e3.png)
![slic3r_bug](https://cloud.githubusercontent.com/assets/11003333/12387458/ee9dcdf2-bdcc-11e5-86da-0a4a463b58a8.png)

Hello

seems like in some cases the solid fill is not calculated correctly (please check Slic3r_bug.png). The issue disappeared when I rotated model by 90 degree (Slic3r_correct.png). Please check attachement.

source file : http://www.thingiverse.com/thing:1102368 (Prusa_i3_RAMBo_V3_bottom_plate)

regards,
Marian

**Comment by lordofhyphens** [comment]
Please read the guidelines, we need the configuration you used at least.

**Comment by mkubi** [comment]
[config.zip](https://github.com/alexrj/Slic3r/files/94539/config.zip)

sorry my fauld. Configuration attached.

**Comment by Vicious-one** [comment]
Same thing here. In fact, the part where infill seems less dense is heavily overextruded.

**Comment by mkubi** [comment]
Seems like overextrusion is applied also to rotated object which I originally thought is good. So far I only noticed the issue just with this particular object.

**Comment by mdelongpre** [comment]
Add me to the list, no matter what I do it seems to overextrude for me as well

**Comment by lordofhyphens** [comment]
I've no idea why it is happening, but I found that if you set the perimeter width to 0.4 (from 0.45) the symptoms go away... but also when you have 1 0.9mm perimeter as well, so it's not the space available doing it apparently. 
![failure_case](https://cloud.githubusercontent.com/assets/31754/16753030/d286027e-47ab-11e6-8fcb-4348942fd743.png)

It's ignoring the solid infill setting completely too -.-;

**Comment by bubnikv** [comment]
This issue certainly has a high priority. I am on vacation this week,
having a phone only. I will look into this the next week. If you could only
assign it to me😉. There is a logic in the infill code to stretch the
extrusion width to fill a top/bottom surface with an integer number of
lines, but that code shall not have this effect.
On Jul 12, 2016 6:35 AM, "Joseph Lenox" <notifications@github.com> wrote:

I've no idea why it is happening, but I found that if you set the perimeter
width to 0.4 (from 0.45) the symptoms go away... but also when you have 1
0.9mm perimeter as well, so it's not the space available doing it
apparently.
[image: failure_case]
<https://cloud.githubusercontent.com/assets/31754/16753030/d286027e-47ab-11e6-8fcb-4348942fd743.png>

It's ignoring the solid infill setting completely too -.-;

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexrj/Slic3r/issues/3210#issuecomment-231935127>, or mute
the thread
<https://github.com/notifications/unsubscribe/AFj5I6MjIoisS_35hxL74f2Hpnfj3KgCks5qUxmjgaJpZM4HGxGj>
.

**Comment by alexrj** [comment]
This is fixed as of current master:

![schermata 2017-03-05 alle 21 31 29](https://cloud.githubusercontent.com/assets/594957/23591073/3237c398-01eb-11e7-805f-17d8d65bb4ce.png)
