### ISSUE TITLE
Gaps filled over infill

### ISSUE THREAD

**Issue by Vicious-one** [alexrj/Slic3r#3281]
Version: 1.2.9-226-gb744947
Linux, GCC 5.3.0, Perl 5.22.1

Sometimes the infill is generated in narrow areas even when gap fill is enabled.

![gap-double-fill](https://cloud.githubusercontent.com/assets/10331220/13905252/e4a49316-eed3-11e5-8953-0c4fdadde94c.png)

STL and config:
[gap-double-fill.zip](https://github.com/alexrj/Slic3r/files/181357/gap-double-fill.zip)

**Comment by markwal** [comment]
Which version are you running?  There was a fix for a similar bug, but if you're running a new version, it could be a regression since the most recent changes were also in the area of gap fill.

@lordofhyphens maybe it's time for a git issue template?

**Comment by Vicious-one** [comment]
@markwal -- I've just built it from master. But this issue is kinda long-standing.

**Comment by markwal** [comment]
Yes, but there were a bunch of recent fixes for precisely this issue, so we need to figure out whether you're seeing the same issue for a different cause, don't have the latest, or still see an unfixed issue.  Also, when giving version info, a commit number is more useful than "master" because "master" changes.

You can use:

git describe --tag

to git a descriptive version number, but report it like that:

git describe --tag says "1.2.9-221-g5ff7511"

**Comment by Vicious-one** [comment]
@markwal -- Done

**Comment by lordofhyphens** [comment]
@markwal got one up, probably could be better though. #3284 3284

**Comment by Vicious-one** [comment]
When Gap fill is disabled, the infill also seems strange:

![gap-double-fill-2](https://cloud.githubusercontent.com/assets/10331220/13907503/f0572cfc-ef08-11e5-9849-1dd76235b8b0.png)

**Comment by Vicious-one** [comment]
The original issue seems to be fixed in 1.2.9-234-g9576973
(At least with that model)
![gap-double-fill-3](https://cloud.githubusercontent.com/assets/10331220/14068107/bafb7f46-f489-11e5-89d4-188e5b572c90.png)

**Comment by alexrj** [comment]
Yes, it was fixed! Thank you for reporting, test cases are always very useful.
