### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by usernamevalis** [alexrj/Slic3r#3301]
Hi 

When I try download Slic3r I get a 403 Forbidden error - the url is :http://dl.slic3r.org/mac/

Thanks

**Comment by lordofhyphens** [comment]
Not seeing the problem when I just  tried; probably just a transient issue with the host or something. Try again :)

**Comment by dchosking** [comment]
I get this same issue on the windows links, I have not been able to download it for months.
Other users are having this same issue
https://www.reddit.com/r/3Dprinting/comments/4pof4w/can_anyone_upload_the_latest_slic3r_for_me_the/

**Comment by lordofhyphens** [comment]
Don't know what is going on, as it just worked for me.

**Comment by lordofhyphens** [comment]
https://bintray.com/lordofhyphens/Slic3r/slic3r_dev

For 1.3.0-dev  (as it comes off of the build server).

**Comment by dchosking** [comment]
![image](https://cloud.githubusercontent.com/assets/11595151/18850924/ea876cda-8439-11e6-8f09-29d45b129219.png)

This is a screen shot of what i get when trying to download, seems like an authentication issue to me

**Comment by lordofhyphens** [comment]
I literally just did a download with no authentication. On my phone. It's something transient at best. At worst it's not something I can do anything about. 

![image](https://cloud.githubusercontent.com/assets/31754/18851079/eececcb4-83ff-11e6-9f08-c8a3653e410e.png)

**Comment by dchosking** [comment]
It is strange, i just tried on my phone and it seems to work just fine. 
My phone is even running on the same network as the pc but i cant seem to download it.

**Comment by lordofhyphens** [comment]
I'd look at your PC/browser, I think we can rule out the server itself in this case.

**Comment by dchosking** [comment]
Right, i am going to grab my work laptop and give that a go, it was formatted around a week ago so should be a good test

**Comment by lordofhyphens** [comment]
I don't know what to tell you, I can't reproduce the problem and I have no access to debug the server itself. Your options are to get the OSX build from Prusa3d.com or build 1.3.0-dev from git or keep digging.

https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-OS-X

**Comment by drakruka** [comment]
I had The same Problem , turned out They were Blocking my country's IP , So i used A VPN and it worked!

**Comment by rspencer01** [comment]
This seems to be a persistent problem.  Recognizing that you don't have access to the server, but that this is a pain for people from certain areas (I had to ssh into a server I owned in a different country), perhaps it might do to put a disclaimer near the link at the least?  Or a link to a mirror?  I'd also perhaps suggest to your host that blocking certain IPs is exceptionally bad practice, as it is hurting your (and hence their) brand.

**Comment by lordofhyphens** [comment]
@alexrj

On Aug 6, 2017 1:19 PM, "Robert Spencer" <notifications@github.com> wrote:

This seems to be a persistent problem. Recognizing that you don't have
access to the server, but that this is a pain for people from certain areas
(I had to ssh into a server I owned in a different country), perhaps it
might do to put a disclaimer near the link at the least? Or a link to a
mirror? I'd also perhaps suggest to your host that blocking certain IPs is
exceptionally bad practice, as it is hurting your (and hence their) brand.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/alexrj/Slic3r/issues/3301#issuecomment-320523259>, or mute
the thread
