### ISSUE TITLE
Feature Request - Generate support only attached to bed.

### ISSUE THREAD

**Issue by mozgy** [alexrj/Slic3r#3310]
Slic3r 1.2.9

please add option to generate support material only attached to bed.
Example would be pipes (or tubes) in + combination. Support should be generated only from bed to outer surface and not any support generated inside pipes.

**Comment by lordofhyphens** [comment]
Pretty sure this is a duplicated request. Will check later when I am not on
my phone. I know that completing this would involve a rewrite of the entire
support algorithm system.

You should probably start thinking of approaches and their pros/cons.

**Comment by jfpion** [comment]
yes is an old request. seems it could be approached with the discuted horizontally space adjustment for the support. if you specify a gap large enough it will be no support in the small hole/tube

**Comment by Patola** [comment]
If that requires a rewrite, that would be a very good opportunity to try
and make supports in zig-zag so that they can be easily detachable by
pulling it from one side, like in simplify3d and cura!

On Thu, May 5, 2016 at 6:13 PM, jfpion <notifications@github.com> wrote:

> yes is an old request. seems it could be approached with the discuted
> horizontally space adjustment for the support. if you specify a gap large
> enough it will be no support in the small hole/tube
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alexrj/Slic3r/issues/3310#issuecomment-217281636>
>



-- 
Cláudio "Patola" Sampaio
MakerLinux Labs - Campinas, SP
Gmail <patola@gmail.com> - Mail EAD <patola@techtraining.eng.br> -
MakerLinux <patola@makerlinux.com.br> - YOUTUBE
<https://www.youtube.com/user/makerlinux>!
Facebook <https://www.facebook.com/patolinux> - Facebook da MakerLinux
<https://www.facebook.com/makerlinux> - Lattes
<http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4763932Z5>

**Comment by lordofhyphens** [comment]
@Patola the support material patterns are all implemented in Perl, take a look at how it's done and you can probably work out how to make a zig-zag. :)
I will happily review any PRs that come in for that.

Similar to how we already have pillars, rectilinear, etc.

**Comment by Patola** [comment]
Hey, I would love it indeed. However, I can't understand the code as it is
now and I find it difficult to find a gentle introduction to
slicing-related algorithms. Do you have any study material to suggest?
Please try and be specific, as I already know that generically there's lots
of path-finding and graph algorithms.

On Tue, May 17, 2016 at 6:02 PM, Joseph Lenox <notifications@github.com>
wrote:

> @Patola <https://github.com/Patola> the support material patterns are all
> implemented in Perl, take a look at how it's done and you can probably work
> out how to make a zig-zag. :)
> I will happily review any PRs that come in for that.
>
> Similar to how we already have pillars, rectilinear, etc.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/alexrj/Slic3r/issues/3310#issuecomment-219852573>
>



-- 
Cláudio "Patola" Sampaio
MakerLinux Labs - Campinas, SP
Gmail <patola@gmail.com> - Mail EAD <patola@techtraining.eng.br> -
MakerLinux <patola@makerlinux.com.br> - YOUTUBE
<https://www.youtube.com/user/makerlinux>!
Facebook <https://www.facebook.com/patolinux> - Facebook da MakerLinux
<https://www.facebook.com/makerlinux> - Lattes
<http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4763932Z5>

**Comment by lordofhyphens** [comment]
Start by studying what's already there; how the existing routines generate
the toolpaths your are looking at (afaik all of the support is generated in
Perl).

lib/Slic3r/Print/SupportMaterial.pm is a good place to start looking. You
don't even have to recompile to see changes because it's in Perl. Just get
it to build from source once and you can tweak the Perl files and reload to
see changes.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
Odds are the place to start is going to be from the Pillars support structure, as the capital construction is more or less what we're looking for here.

I haven't had time to dig through and understand what the current algorithm expects w/r/t data structures in (perl's weak typing makes this a bit opaque, which is very irritating).

**Comment by lordofhyphens** [comment]
@bubnikv provided an implementation for this.

Source: https://github.com/lordofhyphens/Slic3r/tree/infill-over-plate
The build server should have it ready in a bit, and I'll get a PR up after I've looked it over.

**Comment by lordofhyphens** [comment]
@mozgy Try out the new PR/branch (should be up on bintray for win32).
