### ISSUE TITLE
Single layer part concentric infill bug

### ISSUE THREAD

**Issue by forrestp** [alexrj/Slic3r#3380]
### Version

1.2.9
### Operating system type + version

Ubuntu Linux 14.04
### Behavior

Bug report: 

Slicing a 1-layer thick STL with 100% fill density and 0 bottom/top horizontal shells with concentric fill pattern generates gcode that looks like it is using the rectilinear fill pattern. When I scale the STL up to 200%, both layers appear to be using proper concentric fill, so this only seems to be an issue with 1-layer STL files.

Easy workaround is to use concentric pattern for top/bottom fill pattern, and set 1 bottom horizontal shell. But, I decided to report the bug anyways because it is unexpected behavior that confused me.
#### STL/Config (.ZIP) where problem occurs

[bug_report.zip](https://github.com/alexrj/Slic3r/files/333821/bug_report.zip)

**Comment by alexrj** [comment]
This behavior is caused by the solid_infill_below_area setting. Your object is very tiny so the infill was below that threshold, and Slic3r used rectilinear infill.
However since you already set 100% fill density Slic3r should ignore that setting and leave the pattern you chose. I just pushed this minor change. Thank you.
