### ISSUE TITLE
Missing layer in gcode

### ISSUE THREAD

**Issue by kdupke** [alexrj/Slic3r#3544]
[like the template]
### Version

1.2.9-367-g8910b4
github Oct 23 11:50 UTC
1.3.0-dev
### Operating system type + version

openSUSE Leap 42.1
### Behavior

Layer in between is missing. Just left out.

Slicing the attached STL one layer at 27mm is missing. Other layers are fine.

When I create the object with different parameters in openSCAD I still get a missing layer but a different one.

![slicr-1](https://cloud.githubusercontent.com/assets/1151769/19680332/8c88f0ea-9aa5-11e6-9da1-49c85df989f0.jpg)
![slicr-2](https://cloud.githubusercontent.com/assets/1151769/19680331/8c856cf4-9aa5-11e6-87a1-657db7b157f4.jpg)
![slicr-3](https://cloud.githubusercontent.com/assets/1151769/19680333/8c94f4a8-9aa5-11e6-9215-b0b922c37d7f.jpg)
![slicr-4](https://cloud.githubusercontent.com/assets/1151769/19680334/8ca2d4ec-9aa5-11e6-879f-2c69d0786242.jpg)
[uploads_da_c0_39_3e_c9_tween_example3_kd2_mesh_0.25.stl.gz](https://github.com/alexrj/Slic3r/files/550159/uploads_da_c0_39_3e_c9_tween_example3_kd2_mesh_0.25.stl.gz)

**Comment by kdupke** [comment]
I just figured out the original file was optimized for 0.3mm but sliced with 0.25mm. Still wonder as the object looks fine as STL both in the openSCAD view and the slic3r 3d view.

Attached a 0.25mm optimized working version.
[hood_mesh_0.25-A.stl.gz](https://github.com/alexrj/Slic3r/files/550512/hood_mesh_0.25-A.stl.gz)

Not sure this is a real object issue or a slicr issue.

**Comment by bubnikv** [comment]
Looking at the original model, the STL consists of plenty of thin slices. I don't know how you created the model with OpenSCAD, but such a model has a high risk of containing extremely sharp triangles, which are notoriously difficult to process with any computational geometry algorithm. Instead of merging thin slices, you should rather calculate hulls of simple 3D objects in OpenSCAD to achieve smooth organic like transitions. I know, it is difficult.

**Comment by lordofhyphens** [comment]
This is probably not a bug in Slic3r, but the model being funky instead. 
Closing for now, has been no response from @kdupke
