### ISSUE TITLE
M109 vs M104

### ISSUE THREAD

**Issue by kontakt** [alexrj/Slic3r#3650]
### Version
1.2.9a

### Operating system type + version
Win10

### Behavior
Using M104 mid print, rather than M109. The printer I'm using has a less than ideal PID for temperature control, which leads to some instability.

I'm using 230C for the first layer, then 225C for the remaining. The problem arises when the temperature drops to 220C halfway through the second layer and adds a defect region until the temperature gets back into the expected range.

**Comment by lordofhyphens** [comment]
This is generally expected behavior (using M104), as the wait will leave the hotend in printed areas.  You can patch over it yourself with a post-processing script (replace all M104 with M109), or you can fix your PID so it doesn't undershoot that much (reduce the D term is a good start, increase P a little).

You could also add `M109 S[temperature]` to your post-layer-change gcode which would have a similar effect.
