### ISSUE TITLE
Rotation of object direction is wrong

### ISSUE THREAD

**Issue by Louis-Cypher** [alexrj/Slic3r#3667]
### Version
1.2.9 stable

### Operating system type + version
Windows 7

### Behavior
From my perspective the rotation direction of objects around X and Y and Z is wrong. I think the object should be rotated w.r.t the Printer COS not the other way round. According to the right hand rule Slic3r doesn't rotate the object, it rotates the printer

This is a bug

#### STL/Config (.ZIP) where problem occurs
Applies to any object

**Comment by lordofhyphens** [comment]
Please include a few screenshots to show what you mean.

**Comment by Patola** [comment]
I am curious to this bug because Slic3r actually follows the right hand rule (thumb → axis, fingers → rotation direction). Just tested here with an object, in all three axes. Slic3r 1.3.0-dev

**Comment by Louis-Cypher** [comment]
Maybe I am just ill minded but this has disturbed me quite a while and meanwhile I just do the opposite of what intend to do and I am fine....

Here we go. Starting position:
![0degree](https://cloud.githubusercontent.com/assets/10894095/21964035/93210b88-db44-11e6-8bd1-ef9196abbe3c.png)
 Rotate- X -> 90 -> Enter

![90deg](https://cloud.githubusercontent.com/assets/10894095/21964039/a69ee8b0-db44-11e6-9a91-b43067b83842.png)

Done

 From my point of view the beautiful lady should just be laying on her face, if she is the object that turns with respect to the printer, right?

**Comment by Patola** [comment]
I just tested rotation in my slic3r. git master 586d95b28a8e473bdcbd959f1e37d215ae531df5

Loaded file:
![slic3r_465](https://cloud.githubusercontent.com/assets/2991620/21964189/957d26e8-db2e-11e6-80b6-f7060e57a4ac.png)

Right-clicked on it, Rotate → Around X Axis... 90 (positive)

![rotate around x axis_466](https://cloud.githubusercontent.com/assets/2991620/21964204/bb8745a8-db2e-11e6-8a4b-30a8fa8226ca.png)

And this is the result:

![slic3r_467](https://cloud.githubusercontent.com/assets/2991620/21964207/c6e8f964-db2e-11e6-9fc3-b6d4e9713cb4.png)

Seems OK here. The Amitabha went face-down as expected. I have made an illustration of the right-hand rule, see if it was that:

![selection_468](https://cloud.githubusercontent.com/assets/2991620/21964216/f71759e6-db2e-11e6-8e6c-a166cdff0b01.png)

**Comment by Louis-Cypher** [comment]
That's really strange. In your example rotation is correct and we are using the same axis of rotation and the same rotation value.

Here is my config- bundle 
[Slic3r_config_bundle.zip](https://github.com/alexrj/Slic3r/files/706723/Slic3r_config_bundle.zip)
 
May be I made some weird settings changes?

**Comment by Patola** [comment]
I doubt it. I know no configuration options which can change rotation settings....
Can you try and download and compile the latest version from git?

**Comment by Louis-Cypher** [comment]
Sadly I can't on this computer since there is no compiler installed. I could do it on a linux computer but i expect no difference to what you experienced on your computer. Please remember this is a 1.2.9 stable issue.

**Comment by lordofhyphens** [comment]
@Louis-Cypher https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/1.3.0-master-329 for a windows build.

1.2.9 isn't getting any commits to it, so any fixes would go into 1.2.10 (next stable) or 1.3.0 (current).

**Comment by lordofhyphens** [comment]
@Louis-Cypher also, is the model available for download somewhere?

**Comment by Louis-Cypher** [comment]
This issue occurs with any model. I know that there will be no commits to stable. Downloaded the build and will check

**Comment by Louis-Cypher** [comment]
1.3.0. master as expected doesn't have the issue. This can be closed. Am I anyways supposed to report issues in 1.2.9 stable or only ones found in the most current development version?

**Comment by lordofhyphens** [comment]
You can report issues from 1.2.9, but the first question someone will ask is "is it still a problem in 1.3.0-dev?" So be ready to answer ;) 

Things change from full release, often quite a bit.

Especially if there had been a reported issue with it before (my quick search didn't find any for this one). This is standard bug triage--if the symptoms don't show up in current -dev, then there's not much point in going further with it except for academic reasons (that I at least don't have time for).

If you want, you could probably nail down when the behavior changed with a git bisect routine. I am not going to bother. FWIW I never noticed that it was "wrong" myself with 1.2.9. If I had, it wasn't enough to trip my "maybe this is a bug" sense.

I provide the automatic windows builds so that people who use Windows can check 1.3.0-dev (or use it in general).

There's already some major improvements from 1.2.9 (especially around gap fill and infill overextrusion).

**Comment by lordofhyphens** [comment]
I've updated the contributing guidelines to cover this, but who knows who actually reads this :(
https://github.com/alexrj/Slic3r/blob/master/.github/CONTRIBUTING.md

**Comment by Patola** [comment]
Just as a curiosity, by default Simplify3D also sports this "bug" (it follows opposite of the right-hand rule); actually, it does that because by default it flips the Y axis, but if you disable this flip in the preferences, it behaves just like Cura, slic3r and the rest of slicers (I happen to try and learn all of them).

**Comment by lordofhyphens** [comment]
@Patola probably because people don't realize that on an i3 the y axis 0 is
all the way away from you?
