### ISSUE TITLE
Feature request- belt stretch/frame wobble compensation for tall prints

### ISSUE THREAD

**Issue by mrehorst** [alexrj/Slic3r#3838]
My most recent build is a coreXY printer with belt-lifted Z axis.  When the bed is loaded, the belts stretch.  I have measured the amount of stretch in my machine at about 42 um/kg load.  That means that as the print gets heavier, the print layers are going to thicken while getting narrower.  If there was a way to enter the belt stretch value, say 42 um/kg in my case, and have slic3r compensate for the belt stretch by adjusting the layer thickness while maintaining constant extruder flow, even large, heavy prints would come out with uniform layer thickness/extrusion, and accurate height.

In tall printers with beds moving in the Z axis, when the bed is high it is closely coupled to the XY stage that tends to throw the printer around as the parts move.  As the print gets taller, the bed drops and becomes more decoupled from the wobbling top of the printer, producing artifacts in the print surface.  If the speed/acceleration could be adjusted as a function of print height the print artifacts could be minimized.  The same could apply to i3 type machines lifting the X axis in Z.

**Comment by lordofhyphens** [comment]
This and similar things (#2431) has been discussed before, and it's a poor choice to try to fix it in the slicer (belt stretch) I wouldn't even accept a pull request for this.

Tagging @alexrj if he wants to add any comments, but I'm closing this because it's both extremely difficult, a bad place to insert this kind of compensation, and the actual solution is to build your printer better.

The second issue is doable with a post-processing script script very easily (keep track of current Z and modify every F attached to a G1 that has X/Y and E to your scaling factor and every change in acceleration that slic3r does).

Issue is still being closed. In the future keep your requests to ONE thing per issue.
