### ISSUE TITLE
Bad bridging

### ISSUE THREAD

**Issue by swiftgeek** [alexrj/Slic3r#3929]
### Version
8c77f476
### Operating system type + version
Archlinux
### Behavior
![przechwycenie obrazu ekranu_2017-05-03_14-40-08](https://cloud.githubusercontent.com/assets/270845/25661867/9d0fc2e2-3012-11e7-97a5-3838f8ec4733.png)
![przechwycenie obrazu ekranu_2017-05-03_14-41-02](https://cloud.githubusercontent.com/assets/270845/25661865/9cde4c76-3012-11e7-81af-3e712b92c441.png)
Bridge happens along longer distance instead of short one

#### STL/Config (.ZIP) where problem occurs
[bad-bridging-8c77f476.zip](https://github.com/alexrj/Slic3r/files/973377/bad-bridging-8c77f476.zip)

**Comment by swiftgeek** [comment]
Another example
![przechwycenie obrazu ekranu_2017-05-03_20-30-43](https://cloud.githubusercontent.com/assets/270845/25675632/7c0eff90-303f-11e7-873e-7c1eba77e65b.png)
[bridge-to-air.zip](https://github.com/alexrj/Slic3r/files/974306/bridge-to-air.zip)

**Comment by lordofhyphens** [comment]
Is this a recent development (aka regression)?

**Comment by alexrj** [comment]
Simplified test case: [x-end_trim.stl.zip](https://github.com/alexrj/Slic3r/files/990594/x-end_trim.stl.zip)

**Comment by alexrj** [comment]
The problem is caused by this irregular shape in object:
![schermata 2017-05-10 alle 22 52 23](https://cloud.githubusercontent.com/assets/594957/25920811/6dedc1dc-35d3-11e7-829f-31606f760363.png)

Here's a screenshot of the anchor layer (the one below the bridge). The grey shape is the original sliced model. Notice the white gap.
![schermata 2017-05-10 alle 22 53 17](https://cloud.githubusercontent.com/assets/594957/25920868/9876e852-35d3-11e7-9853-95e7c5359b35.png)

**Comment by alexrj** [comment]
Fixed. Bridge detection will now deal with situations like that where lower layer has narrow gaps under the bridge anchors.
