### ISSUE TITLE
Crash on "Export Config Bundle"

### ISSUE THREAD

**Issue by markolo25** [alexrj/Slic3r#3996]
### Version
1.3.0-dev 6a7057b

### Operating system type + version
Windows 10 64-bit Version 1703 (OS Build 15063.296)
### Behavior
When exporting a config bundle the application closes
To Recreate the problem
File > Export Config Bundle > Save > "Application closes on it's own"

using slic3r-debug console 

![image](https://cloud.githubusercontent.com/assets/1953943/26664783/f9203b2e-4648-11e7-9eb2-4f312acee3a7.png)

**Comment by lordofhyphens** [comment]
I suspect that there's a regression from the changes in gui-shortcuts (iterating over all of the configurations). 

Single-config export still works.

**Comment by lordofhyphens** [comment]
Preset::load_config returns immediately if its internal config isn't empty. However, it returns nothing instead of `$self->_config`. 

Since this seems to be one of the only places that expects an immediate return and the normal behavior for Preset::load_config is to return a copy of the config object, we can safely return `$self->_config` during the early abort logic.
