### ISSUE TITLE
Feature Request: Turn off auto centering.

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [alexrj/Slic3r#404]
First off thanks again for all your hard work slic3r is amazing and never stops getting better.

It would be really nice now that you have the GUI to be able to place an item(s) on the build surface without it auto centering every time. Maybe just a check box that says auto centering enabled? This is so when you wear out your build surface in the middle you can print in the corners or along the side and don't need to replace the tape as often. Also so you don't where out your smooth rods in the middle.

**Comment by GilesBathgate** [comment]
@alexrj I am not sure the implementation does what is expected. (or my expectations are incorrect). The change does stop the parts from being auto-arranged, but if I load cube.stl (with its corner fixed to [0,0,0]) it is automatically placed in the center of the bed instead of the co-ordinates specified in the stl.
If I then add another cube2.stl (with its corner fixed to 50,0,0) it places that cube in the center on top of the original:

![image](https://user-images.githubusercontent.com/444143/31716015-148ed3d4-b3fe-11e7-8375-f4a6d17ea3f9.png)

What I was expecting was that the positions should not be altered at all and should just be what was specified in the stl file

![image](https://user-images.githubusercontent.com/444143/31716183-92de241a-b3fe-11e7-9406-b8bf15de3e94.png)

I have created a pull request https://github.com/alexrj/Slic3r/pull/4156 that changes the behaviour so that it matches what I expect (i.e the second screenshot)

**Comment by expertmm** [comment]
see also (underlying issue): #4190

**Comment by GilesBathgate** [comment]
@expertmm Well I think the underlying issue is fixed and merged in PR #4156 . Perhaps you could let me know after testing (a version more recent than Oct 20) it if there is still an issue.

**Comment by expertmm** [comment]
"It would be really nice now that you have the GUI to be able to place an item(s) on the build surface without it auto centering every time." this is the specific part of the issue to which I was referring. For example, even with centering off, in recent git version as described in 4190, all of these end up at the same place. To reproduce:
* Add stl files (attached) to Slic3r (see attached Slic3r screenshots)
* compare result to importing them into other program such as Blender (see attached Blender screenshot)
![after importing all six into blender shows that blender had applied the position before exporting](https://user-images.githubusercontent.com/7557867/33630262-9b416d3a-d9fe-11e7-9509-5c3ccb245c57.jpg)
![after importing all six into slic3r](https://user-images.githubusercontent.com/7557867/33630263-9b59706a-d9fe-11e7-8851-ccd034e92d5e.jpg)
![automatic changes to x and y and hidden modification of z value of origin](https://user-images.githubusercontent.com/7557867/33630264-9b63bb6a-d9fe-11e7-8587-a1df26ededd5.jpg)

[positioning-tests.zip](https://github.com/alexrj/Slic3r/files/1532862/positioning-tests.zip)

**Comment by GilesBathgate** [comment]
@expertmm Ah of course. I deliberately added code to always align to z=0 ( see: https://github.com/alexrj/Slic3r/pull/4156/commits/6faaec5285ab145ec6824ddf2c983cd99565d8e2 )
because I assumed that this is what would be wanted. I guess that assumption should only really be made if there isn't already an existing part of the plater. Alternatively, I guess zeroing to z could be set by a different checkbox in the preferences?

**Comment by expertmm** [comment]
Yes, this z change being optional would be helpful, but z change being kept as a transform instead of applied to the object would be ideal (and allow another method of user control other than a checkbox even if checkbox wasn't there)--that is part of issue 4190. However, the x and y are changed as well, as there are supposed to be two monkeys visible in Slic3r (however they are instead overlapping in the Slic3r screenshot--I added both pairs of eyes, both heads, and both necks as seen in the Blender screenshot).

**Comment by GilesBathgate** [comment]
@expertmm I think the reason is that my change only applies when `$model_object->instances_count == 0` (see: https://git.io/vbZy8 ) I.e when there are not any models already added to the plater. Even so, I can't see where the X,Y values would get changed. I would have to investigate further.

**Comment by expertmm** [comment]
The vertices are definitely being changed whenever origin changes so this may happen while mesh is loaded.

**Comment by GilesBathgate** [comment]
This is the behaviour I see with the latest version:

![image](https://user-images.githubusercontent.com/444143/33632880-f00e7bd4-da06-11e7-893b-8cec78904c28.png)

With a tweak to the code I mentioned (turn off align object to Z = 0), this is the result:
![image](https://user-images.githubusercontent.com/444143/33633642-6f776cbc-da09-11e7-9e0b-47fddaf5e4d8.png)
Is this not what is required?

**Comment by expertmm** [comment]
Oh! I'll look into that and try again. My /usr/bin/slic3r.pl installed with Slic3r-git AUR package is modified 2017-10-13 14:00:32.000000000

**Comment by GilesBathgate** [comment]
@expertmm I've pushed the additional preference tweak here:
https://github.com/GilesBathgate/Slic3r/tree/auto-alignz-preference If you think it's useful I will make a PR.

**Comment by expertmm** [comment]
OK the x, y is resolved as you say--thanks. This along with the z preference may resolve visual alignment issues. However for better control of the models I suggest instead of that workaround which compensates for the secretly applied transform, that Slic3r doesn't secretly apply the transform at all. If that were dealt with, the transforms would be much more clear to programmers and users. This

 screenshot shows that the fix you mentioned compensated for the secret transform by changing the user-controllable transform (except on z, which was also secrectly transformed since otherwise it woudl have a negative number in the screenshot below):
![updated slic3r 2017-12-05 applies transforms on xy](https://user-images.githubusercontent.com/7557867/33635594-75886604-da10-11e7-8eb4-49fcd04f7c15.jpg)

Also it is clear that even the object that remains centered secretly had a transform applied, and then the user-controllable transform was modified to compensate:
![updated slic3r 2017-12-05 applies transforms](https://user-images.githubusercontent.com/7557867/33635620-95ee56ce-da10-11e7-8ce3-fe6c269bb8bc.jpg)

**Comment by GilesBathgate** [comment]
@expertmm Yes I see your point. As an advanced user, I just want slic3r to not mess with my original input geometry locations. I think the issue as pointed out in https://github.com/alexrj/Slic3r/pull/4156#issuecomment-338103793 is that STL is usually aligned to some arbitrary origin which may or may not be sensible with respect to the print origin. I think the concern is mainly about maintaining backwards compatibility and as a newbie user I think its better to have slic3r auto-center/auto-align so as not to a) print at x,y outside the print bounds b) print in mid air c) ram the nozzle into the print bed ;)

**Comment by expertmm** [comment]
for sure, aligning is a sensible default

**Comment by GilesBathgate** [comment]
@expertmm I am not that familiar with the code myself. I don't think there is a distinct place in the code where these transforms are applied, and while I was able to see what changes were needed to add these two little tweaks, the change had an unintended side effect which I tried to address in https://github.com/alexrj/Slic3r/pull/4170 I think it needs one of the maintainers to follow this up.
