### ISSUE TITLE
Use C++ as a Postproccessor Script

### ISSUE THREAD

**Issue by MeetThePatel** [alexrj/Slic3r#4048]
### Version
Version 1.2.9 Mac

How do I use a C++ post processor script as the output to Slic3r. I used to have a Python script, and it worked great in the Print Settings > Output Options > Post-Processing Scripts box. I used to be able to enter the path, and I had the script configured to take the file path as the first argument, and it used to work fine.

But then I switched to C++, and I can't seem to get it to work. I compiled the C++ program into an executable, and when I am on the command line, I can supply the file path similarly to how I used to do it with the Python script, but when I put the path to the compiled C++ program into the Print Settings > Output Options > Post-Processing Scripts box, it doesnt seem to work.

**Comment by alexrj** [comment]
Slic3r just calls the supplied path as an executable, no matter what language is it written in. Make sure you entered the correct absolute path, and that it's executable. Also try to run Slic3r with the `--debug` command line option; it might give you some troubleshooting info.

Also, please use the latest 1.3.0-dev build instead of the old 1.2.9.
