### ISSUE TITLE
Modify GUI --> add new tab

### ISSUE THREAD

**Issue by larajustine** [alexrj/Slic3r#4197]
Hi, I'm trying to add a new option in the settings in order to modify pressure parameters, but I didn't find out which perl file contains the initialization of variables. I added data in PresentEditor.pm but I get this error:
`No **variable_name** in ConfigOptionsGroup config at C:/Slic3r/lib/Slic3r/GUI/OptionsGroup.pm`

Which perl file can I initializate this news variables?

As a last resort, I could modify just the GCode, but I also don't know which perl file I would use.

Any help? :)

**Comment by lordofhyphens** [comment]
Sorry it's taken me this long to get to you. 
I have a wiki entry for this. A good heuristic to find everything is to check for an already-existing option and see where it is defined. Feel free to add notes to the wiki.

https://github.com/alexrj/Slic3r/wiki/Code%3A-Adding-new-option-to-GUI-CLI

**Comment by larajustine** [comment]
How can I do this check? 
I think just running `perl slic3r.pl` is not actualizing the .o files.

**Comment by lordofhyphens** [comment]
You have to run Build.pl to install the compiled library.

On the Perl side it is immediate upon restart of Slic3r

**Comment by larajustine** [comment]
Even doing this, the same error occurs. 
Do you think this is because the Wx error? When I run `perl build.pl --gui` I get this error:
`Installing Wx failed. See C:\Users\laraj\.cpanm\work\1512136829.5664\build.log for details. Retry with --force to force install it.`
`Don't worry, this module is optional.`

But it says it's optional :(

**Comment by lordofhyphens** [comment]
It is not optional for the GUI. It is optional for the CLI.

I suggest that if you are on Windows, use Slic3r perl and the prebuilt
local-lib archive I produced for it.


On Dec 1, 2017 8:11 AM, "larajustine" <notifications@github.com> wrote:

Even doing this, the same error occurs.
Do you think this is because the Wx error? When I run perl build.pl --gui I
get this error:
Installing Wx failed. See C:\Users\laraj\.cpanm\work\1512136829.5664\build.log
for details. Retry with --force to force install it.
Don't worry, this module is optional.

But it says it's optional :(

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/alexrj/Slic3r/issues/4197#issuecomment-348504189>, or mute
the thread

**Comment by larajustine** [comment]
Mute the thread? What do you mean?

**Comment by lordofhyphens** [comment]
Mute the thread is a message from GitHub (I sometimes reply via email). Ignore it.

**Comment by lordofhyphens** [comment]
Regarding your error, sounds like you broke something when editing the XS side of things.
