### ISSUE TITLE
Single walls and dimensional accuracy

### ISSUE THREAD

**Issue by tdeyle** [alexrj/Slic3r#626]
### Slic3r version: 
0.9.1
### Operating system type + version:
Windows 7x64

### STL used:
[20mm Hollow Box](http://www.thingiverse.com/download:17279)

### Issue Explanation
I expect to see straight sides to the top of the object, but I get a "lip" of extra material that is printed off at the top layer, anywhere where there is a solid filled layer. This using automatic extrusion width settings in 0.9.1.

Using Slic3r 0.7.1, 0.7.2b, and Cura 12.08, I do not get this extra material. 

I have adjusted the Extrusion Width Settings in the Advanced tab, see config, and the lip is less pronounced, but still there.

### Config Files for each:
[Cura](http://pastebin.com/H4p8DMTZ)
[0.9.1 Adjusted](http://pastebin.com/P6bJVbCB)
[0.9.1 Automatic] (http://pastebin.com/Zhbdy6Rp)
[0.7.2b] (http://pastebin.com/LwbWw3Za)
[0.7.1] (http://pastebin.com/452B2MuY)

#### 0.9.1 Automatic:
![0.9.1 Automatic] (https://lh3.googleusercontent.com/-7XMWnaAEq40/UC6fJDAqNtI/AAAAAAAAHqA/hRNpz-xk0Cs/s644/091not.jpg)

#### 0.9.1 Adjusted:
![0.9.1 Adjusted](https://lh5.googleusercontent.com/-kOQ_-rziENc/UC6fIvW2iNI/AAAAAAAAHqI/vljXhs5UN8w/s574/091adj.jpg)

#### 0.7.2b:
![0.7.2b] (https://lh3.googleusercontent.com/-KktNQrsJe8Q/UC6fIo1h-hI/AAAAAAAAHp0/DNQDdH8CGME/s773/072b.jpg)

#### 0.7.1:
![0.7.1] (https://lh4.googleusercontent.com/-vwvXTF37UE4/UC6fIloTOMI/AAAAAAAAHp4/-6oic9i8WsE/s828/071.jpg)

#### CURA:
![Cura](https://lh3.googleusercontent.com/-7usY7Ved918/UC6fJWTxtcI/AAAAAAAAHqE/qcsUpODHOIg/s666/Cura.JPG)

#### Slic3r 0.9.1 Automatic:
![0.9.1 Automatic](https://lh4.googleusercontent.com/-gA3tzl5qtLY/UC6fK4lcD8I/AAAAAAAAHqg/qSAROkUTAeU/s675/Slic3r+091.JPG)

#### Slic3r 0.9.1 Adjusted :
![0.9.1 Adjusted](https://lh6.googleusercontent.com/-N_nGdUxIbxk/UC6fJ34qCHI/AAAAAAAAHqU/8GY8LdUioBk/s675/Slic3r+091+with+adjustments.JPG)

#### Cura:
![Cura](https://lh6.googleusercontent.com/-vZyHDwiFkkI/UC6fJ4DKPkI/AAAAAAAAHqc/a6N6JkcrFig/s675/CuraD.JPG)

**Comment by alexrj** [comment]
So, I tested this with current master (1.3.0-dev). The automatic extrusion width does not trigger the original issue because we're now using a thinner default for external perimeters:

![schermata 2016-03-26 a 19 02 09](https://cloud.githubusercontent.com/assets/594957/14061637/6689c4b8-f385-11e5-8f57-d666f01f5c32.png)

So, two loops actually fit in the external walls and the thin wall algorithm is not triggered at all:

![schermata 2016-03-26 a 19 02 13](https://cloud.githubusercontent.com/assets/594957/14061645/7668a89a-f385-11e5-960b-e1ae037576b1.png)

I set a manual extrusion width to 0.7mm in order to trigger the thin wall algorithm, and I'm happy to confirm that thanks to the recent implementation of adaptive-width thin walls there's no loss in dimensional accuracy, as both thin walls and normal layers are perfectly aligned:

![schermata 2016-03-26 a 19 01 42](https://cloud.githubusercontent.com/assets/594957/14061660/fe173a2c-f385-11e5-9259-954d97da6b0b.png)
![schermata 2016-03-26 a 19 01 47](https://cloud.githubusercontent.com/assets/594957/14061664/11583352-f386-11e5-915b-ac7feaa2a791.png)
