### ISSUE TITLE
slic3r isn't using XDG_* env variables

### ISSUE THREAD

**Issue by swiftgeek** [alexrj/Slic3r#832]
Mainly it should support XDG_CONFIG_HOME

Maybe it should be GetDocumentsDir
http://trac.wxwidgets.org/browser/wxWidgets/trunk/src/unix/stdpaths.cpp (Ctrl-F XDG_CONFIG_HOME)

**Comment by Lucki** [comment]
wxWidgets supports XDG since version `3.1.1` ([merged 15.03.2017](https://github.com/wxWidgets/wxWidgets/pull/433), [released 19.02.2018](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.1.1)).
Slic3r seems to use wxPerl which had it's last [release `0.9932` 18.04.2017](https://metacpan.org/changes/distribution/Wx) so the important parts may be missing. However I wasn't able to find any documentation on how to access the `Wx::StandardPaths` even through it's already used in the code.

If it's possible to access the underlying functions this should be quite easy to implement:
1. Set [`wxStandardPaths::SetFileLayout(FileLayout_XDG)`](https://docs.wxwidgets.org/trunk/classwx_standard_paths.html#af5eb9a009b9fd81b748e26d099bb4e89)

That's it but while we're at it we could also enhance the used folder.
The following steps are optional:

2. Change `GetUserDataDir` to [`GetUserConfigDir`](https://docs.wxwidgets.org/3.0/classwx_standard_paths.html#a7c7cf595d94d29147360d031647476b0) since only config files are stored anyway.
3. Because of the previous change it's now needed to append the [`wxAppConsole::GetAppName()`](https://docs.wxwidgets.org/3.0/classwx_app_console.html#a2bfe9c53c57d61f8b115705796f258eb) to the folder path.

Either if it's possible or not this feature request should be reopened as Slic3r needs some changes to adapt to the standard.

**Comment by lordofhyphens** [comment]
wxPerl only supports wxWidgets 3.0.4, and it's not very feasible to access the underlying functions last I checked (not w/o modifications to wxPerl).  I'd accept work on this for the C++ GUI (which is under work).

**Comment by lordofhyphens** [comment]
(I know because I spent a little bit of time trying to get wxPerl built with 3.1 unsuccessfully).

**Comment by lordofhyphens** [comment]
@Lucki I'd prefer to put a double check in there. First check UserDataDir ~/.Slic3r, then move to UserConfigDir.
