### ISSUE TITLE
SVG export options

### ISSUE THREAD

**Issue by alexrj** [alexrj/Slic3r#919]
Let's discuss what needs to be customizable in SVG export.

I'll start with a couple points:

* white/black or black/white
* red instead of black
* map print layers to SVG layers or groups or individual files
* use single paths with evenodd fill type instead of overlapping paths

**Comment by lordofhyphens** [comment]
@alexrj Can this be closed?

**Comment by edwyn** [comment]
yes

**Comment by lordofhyphens** [comment]
Huzzah

**Comment by gege2b** [comment]
Hi there.
I know it's closed but I think it's better to add my two cents here, instead of creating a new Feature Request.
Sorry in advance if I'm wrong

I would love to be able to export infill in SVG (I built a 2D drawing machine and would love to see it drawing honeycomb-filled shapes or whatever)

For the same reason, It would be nice if we can choose only one layer to export, but it's not a top priority, Slic3r being a 3D Slicer after all (onecan deal with inkscape or whatever to delete unwanted layers after export)

**Comment by lordofhyphens** [comment]
Create a new feature request if you want something changed.
