### ISSUE TITLE
Different infill patterns for top and bottom

### ISSUE THREAD

**Issue by alexrj** [alexrj/Slic3r#945]
@jebba says:

```
Some infills are good for the 
bottom layer (rectilinear) but others look cleaner on the top 
(concentric). Concentric doesn't stick to the plate as well as 
rectilinear.
```

**Comment by lordofhyphens** [comment]
Things that haven't happened yet: this. 

Suggestion is to keep the top/bottom and then add an additional override for one of them (I guess bottom would be overridden?)

**Comment by alexrj** [comment]
Done. We now have two distinct settings: *top_infill_pattern* and *bottom_infill_pattern*. The former `--external-fill-pattern` switch now acts like a shortcut. Old config files are supported as well, so this is a retrocompatible change.

**Comment by Patola** [comment]
Updated to latest HEAD, filled the top and bottom accordingly, but it seems it did not change anything. Instead of changing the top to concentrical (both were rectilinear before), it remained rectilinear. 

![selection_848](https://cloud.githubusercontent.com/assets/2991620/23831947/ef911868-0709-11e7-9b06-c7ca7e0b0698.png)

Before setting this (both were rectilinear):
![slic3r_847](https://cloud.githubusercontent.com/assets/2991620/23831950/00b7f6a2-070a-11e7-972e-23a2e6cbc20c.png)

After setting this (tried even to export g-code to force reslice, to no avail):
![slic3r_849](https://cloud.githubusercontent.com/assets/2991620/23831957/17188ec0-070a-11e7-90b8-04f610d89bd5.png)

**Comment by Patola** [comment]
Shape is one I did quickly on openscad, I am attaching it
[top_stl.zip](https://github.com/alexrj/Slic3r/files/836516/top_stl.zip)

**Comment by Patola** [comment]
And I just realized that for the bottom infill pattern, if I set it to concentric, it is concentric only for the very first layer, afterwards becoming rectilinear.
![selection_850](https://cloud.githubusercontent.com/assets/2991620/23831981/ab9638e0-070a-11e7-974c-abc1ee56b441.png)
![selection_851](https://cloud.githubusercontent.com/assets/2991620/23831982/b38872a2-070a-11e7-8ccc-48ab95d3cda3.png)

**Comment by lordofhyphens** [comment]
The fill becoming rectilinear for the other solid layers is normal and
expected behavior. All internal solid infill is rectilinear. Changing the
top/bottom fill will always effect outer layers only.
