### ISSUE TITLE
[Feature Request] Add comment to gcode at begin and end of skirt and brim

### ISSUE THREAD

**Issue by Itchetiky** [alexrj/Slic3r#963]
I find at times I cut out all sections of generated gcode except the skirt and at time the brim. I do this to validate placement on the heated bed.

Rather then request another UI addition in the form of a 'generate skirt only' button, I'd like to request that the gcode generate add a comment before and after the skirt and brim sections.

Thank you. Slic3r is working very well for me again.

**Comment by donaldrobins007** [comment]
We read your blog and it is very beautiful and the content is also good. You have described the fabric and I liked it so thank you. You can use many items to decorate your bedroom like one of them is a bead skirt which enhances the beauty of your bed. And the work of hiding the low stuff kept in the base room is there and it also keeps the stuff kept under your bed away from the eyes of the people. And let us tell you that there are many types of <a href="https://www.aanyalinen.com/collections/18-bed-skirts"rel="dofollow">18 inch bed skirt</a> and you can buy them according to your need.

**Comment by donaldrobins007** [comment]
We read your blog and it is very beautiful and the content is also good, you have well described the fabric well and I liked it so thank you,The [18-inch bed skirt](<a href="https://www.aanyalinen.com/collections/18-bed-skirts"rel="dofollow">18 inch bed skirt</a>) stable bliss is a delightful, simplistic trimmed valance that without difficulty suits into any bedroom way to its minimalist style. It is made with four hundred threads remembered due to the fact it's far from natural cotton. But no matter its comfortable and low-key design.

**Comment by donaldrobins007** [comment]
We read your blog and it is very beautiful and the content is also good. You have described the fabric and I liked it so thank you, <a href="https://www.aanyalinen.com/collections/18-bed-skirts"rel="dofollow">18 inch bed skirt</a>. Generally people use beautiful bed skirts to enhance the beauty of their bed. Because this skirt makes you and your bedroom feel good and also looks beautiful to the guests coming to your house, aanyalinen is on the way to meet all your bedding needs and you can use these bedding products to have a pleasant feeling.
